#ifndef _INSTALL_INVIRVOL_H_
#define _INSTALL_INVIRVOL_H_

typedef struct _INSTALL_INVIRVOL_DATA
{
    TCHAR* DriverName;
    TCHAR* PathAndFileName;
}INSTALL_INVIRVOL_DATA , *PINSTALL_INVIRVOL_DATA;

typedef struct _UNINSTALL_INVIRVOL_DATA
{
    TCHAR* DriverName;
}UNINSTALL_INVIRVOL_DATA, *PUNINSTALL_INVIRVOL_DATA;

typedef struct _START_INVIRVOL_DATA
{
    TCHAR* DriverName;
}START_INVIRVOL_DATA , *PSTART_INVIRVOL_DATA;

typedef struct _STOP_INVIRVOL_DATA
{
    TCHAR* DriverName;
}STOP_INVIRVOL_DATA , *PSTOP_INVIRVOL_DATA;

DRSTATUS InstallInVirVolDriver(INSTALL_INVIRVOL_DATA &InstallData);
DRSTATUS UninstallInVirVolDriver(UNINSTALL_INVIRVOL_DATA &UninstallData);
DRSTATUS StartInVirVolDriver(START_INVIRVOL_DATA &StartData);
DRSTATUS StopInVirVolDriver(STOP_INVIRVOL_DATA &StopData);

#endif
