#ifndef _INSTALLER_ERRORS
#define _INSTALLER_ERRORS

#include <map>
#include <boost/assign.hpp>
#include "json_reader.h"

#define ERRORCODE_TO_STRING(arg) (#arg)

namespace RcmClientLib
{
    class ExtendedError
    {
    public:
        std::string error_name;
        std::map<std::string, std::string> error_params;
        std::string default_message;

        void serialize(JSON::Adapter& adapter)
        {
            JSON::Class root(adapter, "ExtendedError", false);

            JSON_E(adapter, error_name);
            JSON_KV_E(adapter, "error_params", error_params);
            JSON_T(adapter, default_message);
        }
    };

    class ExtendedErrors
    {
    public:
        std::vector<ExtendedError> Errors;

        void serialize(JSON::Adapter& adapter)
        {
            JSON::Class root(adapter, "ExtendedErrors", false);

            JSON_T(adapter, Errors);
        }
    };

    enum InstallerErrorCodes
    {
        AGENT_INSTALLATION_SUCCESS = 0,
        AGENT_INSTALLATION_INTERNAL_ERROR = 1,
        AGENT_INSTALL_FATAL_ERROR = 4,
        AGENT_INSTALL_PREPARE_STAGE_FAILED = 7,
        AGENT_INSTALL_PREPARE_STATE_FAILED_REBOOTREQUIRED = 8,
        AGENT_INSTALL_SPACE_NOT_AVAILABLE = 10,
        AGENT_EXISTS_DIFF_VERSION = 11,
        AGENT_EXISTS_REGISTEREDWITH_DIFF_CS = 13,
        AGENT_INSTALL_INVALID_CS_IP_PORT_PASSPHRASE = 14,
        AGENT_INSTALL_PREV_INSTALL_DIR_DELETE_FAILED = 15,
        AGENT_INSTALL_DOTNET35_MISSING = 16,
        AGENT_INSTALLED_REGISTER_FAILED = 17,
        AGENT_INSTALL_VMWARE_TOOLS_NOT_RUNNING = 18,
        AGENT_INSTALL_UNSUPPORTED_OS = 42,
        AGENT_INSTALL_SERVICES_STOP_FAILED = 43,
        AGENT_INSTALL_SERVICES_START_FAILED = 44,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED = 45,
        AGENT_INSTALL_DRIVER_MANIFEST_INSTALLATION_FAILED = 46,
        AGENT_INSTALL_DRIVER_ENTRY_REGISTRY_UPDATE_FAILED = 47,
        AGENT_INSTALL_FAILED_TO_SET_SERVICE_STARTUP_TYPE = 48,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_OUT_OF_MEMORY = 50,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_DATABASE_LOCKED = 51,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_ALREADY_EXISTS = 52,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_MARKED_FOR_DELETION = 53,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_CSSCRIPT_ACCESS_DENIED = 54,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_PATH_NOT_FOUND = 55,
        AGENT_INSTALL_FAILED_TO_CREATE_SYMLINKS = 56,
        AGENT_INSTALL_FAILED_TO_INSTALL_AND_CONFIGURE_SERVICES = 57,
        AGENT_INSTALL_PREV_INSTALL_REBOOT_PENDING = 62,
        AGENT_INSTALL_FAILED_WITH_VSS_ISSUE = 63,
        AGENT_INSTALL_BOOT_DRIVER_NOT_AVAILABLE = 64,
        AGENT_INSTALL_FAILED_ON_UNIFIED_SETUP = 65,
        AGENT_INSTALL_MASTER_TARGET_EXISTS = 75,
        AGENT_INSTALL_PLATFORM_MISMATCH = 76,
        AGENT_INSTALL_HOST_NAME_NOT_FOUND = 91,
        AGENT_INSTALL_THIRDPARTY_NOTICES_NOT_AVAILABLE = 93,
        AGENT_INSTALL_LOCALE_NOT_AVAILABLE = 94,
        AGENT_INSTALL_RPM_COMMAND_NOT_AVAILABLE = 95,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_ERRORS = 97,
        AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_WARNINGS = 98,
        AGENT_INSTALL_PREREQS_FAIL = 99,
        AGENT_INSTALL_CERT_GEN_FAIL = 110,
        AGENT_INSTALL_LINUX_INSUFFICIENT_DISK_SPACE = 112,
        AGENT_INSTALL_PREV_INSTALL_NOT_FOUND = 120,
        AGENT_INSTALL_KERNEL_NOT_SUPPORTED = 145,
        AGENT_INSTALL_LINUX_VERSION_NOT_SUPPORTED = 147,
        AGENT_INSTALL_OPERATING_SYSTEM_NOT_SUPPORTED = 149,
        AGENT_INSTALL_DRIVER_INSTALLATION_FAILED = 150,
        AGENT_INSTALL_UPGRADE_PLATFORM_CHANGE_NOT_SUPPORTED = 151,
        AGENT_INSTALL_CONF_FILE_COPY_FAILED = 153,
        AGENT_INSTALL_INSTALLATION_DIRECTORY_ABS_PATH_NEEDED = 156,
        AGENT_INSTALL_TEMP_FOLDER_CREATION_FAILED = 158,
        AGENT_INSTALL_RPM_INSTALLATION_FAILED = 159,
        AGENT_INSTALL_INITRD_BACKUP_FAILED = 162,
        AGENT_INSTALL_INITRD_RESTORE_FAILED = 163,
        AGENT_INSTALL_INITRD_IMAGE_UPDATE_FAILED = 164,
        AGENT_INSTALL_SNAPSHOT_DRIVER_IN_USE = 166,
        AGENT_INSTALL_SNAPSHOT_DRIVER_UNLOAD_FAILED = 167,
        AGENT_INSTALL_HOST_ENTRY_NOTFOUND = 174,
        AGENT_INSTALL_INSUFFICIENT_SPACE_IN_ROOT = 176,
        AGENT_INSTALL_PARTITION_SPACE_NOT_AVAILABLE = 177,
        AGENT_INSTALL_LIS_COMPONENTS_NOT_AVAILABLE = 178,
        AGENT_INSTALL_INVALID_VX_INSTALLATION_OPTIONS = 179,
        AGENT_INSTALL_CACHE_FOLDER_CREATION_FAILED = 180,
        AGENT_INSTALL_INSUFFICIENT_DISKSPACE = 189,
        AGENT_INSTALL_CREATE_TEMPDIR_FAILED = 195,
        AGENT_INSTALL_CURRENT_KERNEL_NOT_SUPPORTED = 208,
        AGENT_INSTALL_LINUX_RECOMMENDED_REBOOT = 209,   // Not defined in SRS
        AGENT_INSTALLER_FILE_NOT_FOUND = 1001,
        AGENT_INSTALL_MSI_INSTALLATION_FAILED = 1603,
        AGENT_INSTALL_MUTEX_ACQUISITION_FAILED = 1618,
        AGENT_INSTALL_EXIT_STATUS_FILE_NOT_FOUND = 2002,
        AGENT_INSTALL_WINDOWS_RECOMMENDED_REBOOT = 3010 // Not defined in SRS
    };

    const std::map<int, std::string> errorCodeMap = boost::assign::map_list_of
        (AGENT_INSTALLATION_SUCCESS, ERRORCODE_TO_STRING(AGENT_INSTALLATION_SUCCESS))
        (AGENT_EXISTS_DIFF_VERSION, ERRORCODE_TO_STRING(AGENT_EXISTS_DIFF_VERSION))
        (AGENT_EXISTS_REGISTEREDWITH_DIFF_CS, ERRORCODE_TO_STRING(AGENT_EXISTS_REGISTEREDWITH_DIFF_CS))
        (AGENT_INSTALL_FATAL_ERROR, ERRORCODE_TO_STRING(AGENT_INSTALL_FATAL_ERROR))
        (AGENT_INSTALL_PREPARE_STAGE_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_PREPARE_STAGE_FAILED))
        (AGENT_INSTALL_PREPARE_STATE_FAILED_REBOOTREQUIRED, ERRORCODE_TO_STRING(AGENT_INSTALL_PREPARE_STATE_FAILED_REBOOTREQUIRED))
        (AGENT_INSTALL_INVALID_CS_IP_PORT_PASSPHRASE, ERRORCODE_TO_STRING(AGENT_INSTALL_INVALID_CS_IP_PORT_PASSPHRASE))
        (AGENT_INSTALL_UNSUPPORTED_OS, ERRORCODE_TO_STRING(AGENT_INSTALL_UNSUPPORTED_OS))
        (AGENT_INSTALL_SERVICES_STOP_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_SERVICES_STOP_FAILED))
        (AGENT_INSTALL_SERVICES_START_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_SERVICES_START_FAILED))
        (AGENT_INSTALL_HOST_ENTRY_NOTFOUND, ERRORCODE_TO_STRING(AGENT_INSTALL_HOST_ENTRY_NOTFOUND))
        (AGENT_INSTALL_INSUFFICIENT_DISKSPACE, ERRORCODE_TO_STRING(AGENT_INSTALL_INSUFFICIENT_DISKSPACE))
        (AGENT_INSTALL_CREATE_TEMPDIR_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_CREATE_TEMPDIR_FAILED))
        (AGENT_INSTALLER_FILE_NOT_FOUND, ERRORCODE_TO_STRING(AGENT_INSTALLER_FILE_NOT_FOUND))
        (AGENT_INSTALL_PREV_INSTALL_DIR_DELETE_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_PREV_INSTALL_DIR_DELETE_FAILED))
        (AGENT_INSTALL_PREV_INSTALL_REBOOT_PENDING, ERRORCODE_TO_STRING(AGENT_INSTALL_PREV_INSTALL_REBOOT_PENDING))
        (AGENT_INSTALL_DOTNET35_MISSING, ERRORCODE_TO_STRING(AGENT_INSTALL_DOTNET35_MISSING))
        (AGENT_INSTALLED_REGISTER_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALLED_REGISTER_FAILED))
        (AGENT_INSTALL_FAILED_WITH_VSS_ISSUE, ERRORCODE_TO_STRING(AGENT_INSTALL_FAILED_WITH_VSS_ISSUE))
        (AGENT_INSTALLATION_INTERNAL_ERROR, ERRORCODE_TO_STRING(AGENT_INSTALLATION_INTERNAL_ERROR))
        (AGENT_INSTALL_PREV_INSTALL_NOT_FOUND, ERRORCODE_TO_STRING(AGENT_INSTALL_PREV_INSTALL_NOT_FOUND))
        (AGENT_INSTALL_KERNEL_NOT_SUPPORTED, ERRORCODE_TO_STRING(AGENT_INSTALL_KERNEL_NOT_SUPPORTED))
        (AGENT_INSTALL_LINUX_VERSION_NOT_SUPPORTED, ERRORCODE_TO_STRING(AGENT_INSTALL_LINUX_VERSION_NOT_SUPPORTED))
        (AGENT_INSTALL_BOOT_DRIVER_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_BOOT_DRIVER_NOT_AVAILABLE))
        (AGENT_INSTALL_FAILED_ON_UNIFIED_SETUP, ERRORCODE_TO_STRING(AGENT_INSTALL_FAILED_ON_UNIFIED_SETUP))
        (AGENT_INSTALL_CURRENT_KERNEL_NOT_SUPPORTED, ERRORCODE_TO_STRING(AGENT_INSTALL_CURRENT_KERNEL_NOT_SUPPORTED))
        (AGENT_INSTALL_LIS_COMPONENTS_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_LIS_COMPONENTS_NOT_AVAILABLE))
        (AGENT_INSTALL_INSUFFICIENT_SPACE_IN_ROOT, ERRORCODE_TO_STRING(AGENT_INSTALL_INSUFFICIENT_SPACE_IN_ROOT))
        (AGENT_INSTALL_SPACE_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_SPACE_NOT_AVAILABLE))
        (AGENT_INSTALL_VMWARE_TOOLS_NOT_RUNNING, ERRORCODE_TO_STRING(AGENT_INSTALL_VMWARE_TOOLS_NOT_RUNNING))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED))
        (AGENT_INSTALL_DRIVER_MANIFEST_INSTALLATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_DRIVER_MANIFEST_INSTALLATION_FAILED))
        (AGENT_INSTALL_MASTER_TARGET_EXISTS, ERRORCODE_TO_STRING(AGENT_INSTALL_MASTER_TARGET_EXISTS))
        (AGENT_INSTALL_PLATFORM_MISMATCH, ERRORCODE_TO_STRING(AGENT_INSTALL_PLATFORM_MISMATCH))
        (AGENT_INSTALL_DRIVER_ENTRY_REGISTRY_UPDATE_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_DRIVER_ENTRY_REGISTRY_UPDATE_FAILED))
        (AGENT_INSTALL_PREREQS_FAIL, ERRORCODE_TO_STRING(AGENT_INSTALL_PREREQS_FAIL))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_ERRORS, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_ERRORS))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_WARNINGS, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_WITH_WARNINGS))
        (AGENT_INSTALL_UPGRADE_PLATFORM_CHANGE_NOT_SUPPORTED, ERRORCODE_TO_STRING(AGENT_INSTALL_UPGRADE_PLATFORM_CHANGE_NOT_SUPPORTED))
        (AGENT_INSTALL_HOST_NAME_NOT_FOUND, ERRORCODE_TO_STRING(AGENT_INSTALL_HOST_NAME_NOT_FOUND))
        (AGENT_INSTALL_INSTALLATION_DIRECTORY_ABS_PATH_NEEDED, ERRORCODE_TO_STRING(AGENT_INSTALL_INSTALLATION_DIRECTORY_ABS_PATH_NEEDED))
        (AGENT_INSTALL_PARTITION_SPACE_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_PARTITION_SPACE_NOT_AVAILABLE))
        (AGENT_INSTALL_OPERATING_SYSTEM_NOT_SUPPORTED, ERRORCODE_TO_STRING(AGENT_INSTALL_OPERATING_SYSTEM_NOT_SUPPORTED))
        (AGENT_INSTALL_THIRDPARTY_NOTICES_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_THIRDPARTY_NOTICES_NOT_AVAILABLE))
        (AGENT_INSTALL_LOCALE_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_LOCALE_NOT_AVAILABLE))
        (AGENT_INSTALL_RPM_COMMAND_NOT_AVAILABLE, ERRORCODE_TO_STRING(AGENT_INSTALL_RPM_COMMAND_NOT_AVAILABLE))
        (AGENT_INSTALL_CONF_FILE_COPY_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_CONF_FILE_COPY_FAILED))
        (AGENT_INSTALL_RPM_INSTALLATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_RPM_INSTALLATION_FAILED))
        (AGENT_INSTALL_TEMP_FOLDER_CREATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_TEMP_FOLDER_CREATION_FAILED))
        (AGENT_INSTALL_DRIVER_INSTALLATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_DRIVER_INSTALLATION_FAILED))
        (AGENT_INSTALL_CACHE_FOLDER_CREATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_CACHE_FOLDER_CREATION_FAILED))
        (AGENT_INSTALL_SNAPSHOT_DRIVER_IN_USE, ERRORCODE_TO_STRING(AGENT_INSTALL_SNAPSHOT_DRIVER_IN_USE))
        (AGENT_INSTALL_SNAPSHOT_DRIVER_UNLOAD_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_SNAPSHOT_DRIVER_UNLOAD_FAILED))
        (AGENT_INSTALL_INVALID_VX_INSTALLATION_OPTIONS, ERRORCODE_TO_STRING(AGENT_INSTALL_INVALID_VX_INSTALLATION_OPTIONS))
        (AGENT_INSTALL_MUTEX_ACQUISITION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_MUTEX_ACQUISITION_FAILED))
        (AGENT_INSTALL_LINUX_INSUFFICIENT_DISK_SPACE, ERRORCODE_TO_STRING(AGENT_INSTALL_LINUX_INSUFFICIENT_DISK_SPACE))
        (AGENT_INSTALL_CERT_GEN_FAIL, ERRORCODE_TO_STRING(AGENT_INSTALL_CERT_GEN_FAIL))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_OUT_OF_MEMORY, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_OUT_OF_MEMORY))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_DATABASE_LOCKED, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_DATABASE_LOCKED))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_ALREADY_EXISTS, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_ALREADY_EXISTS))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_MARKED_FOR_DELETION, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_SERVICE_MARKED_FOR_DELETION))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_CSSCRIPT_ACCESS_DENIED, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_CSSCRIPT_ACCESS_DENIED))
        (AGENT_INSTALL_VSS_INSTALLATION_FAILED_PATH_NOT_FOUND, ERRORCODE_TO_STRING(AGENT_INSTALL_VSS_INSTALLATION_FAILED_PATH_NOT_FOUND))
        (AGENT_INSTALL_MSI_INSTALLATION_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_MSI_INSTALLATION_FAILED))
        (AGENT_INSTALL_FAILED_TO_SET_SERVICE_STARTUP_TYPE, ERRORCODE_TO_STRING(AGENT_INSTALL_FAILED_TO_SET_SERVICE_STARTUP_TYPE))
        (AGENT_INSTALL_INITRD_BACKUP_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_INITRD_BACKUP_FAILED))
        (AGENT_INSTALL_INITRD_RESTORE_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_INITRD_RESTORE_FAILED))
        (AGENT_INSTALL_INITRD_IMAGE_UPDATE_FAILED, ERRORCODE_TO_STRING(AGENT_INSTALL_INITRD_IMAGE_UPDATE_FAILED))
        (AGENT_INSTALL_FAILED_TO_CREATE_SYMLINKS, ERRORCODE_TO_STRING(AGENT_INSTALL_FAILED_TO_CREATE_SYMLINKS))
        (AGENT_INSTALL_FAILED_TO_INSTALL_AND_CONFIGURE_SERVICES, ERRORCODE_TO_STRING(AGENT_INSTALL_FAILED_TO_INSTALL_AND_CONFIGURE_SERVICES))
        (AGENT_INSTALL_EXIT_STATUS_FILE_NOT_FOUND, ERRORCODE_TO_STRING(AGENT_INSTALL_EXIT_STATUS_FILE_NOT_FOUND));

    std::string GetInstallerErrorString(int exitcode)
    {
        std::map<int, std::string>::const_iterator itr = errorCodeMap.find(exitcode);
        if (itr != errorCodeMap.end())
        {
            return itr->second;
        }
        return std::string();
    }
}


#endif // !_INSTALLER_ERRORS
