/*
+------------------------------------------------------------------------------------+
Copyright(c) Microsoft Corp. 2016
+------------------------------------------------------------------------------------+
File		:	RcmClientErrorCodes.h

Description	:   error codes that are returned from RcmClient class objects.

+------------------------------------------------------------------------------------+
*/
#ifndef _RCM_CLIENT_ERROR_CODES_H
#define _RCM_CLIENT_ERROR_CODES_H

#define RCM_CLIENT_MODULE_BASE_ERROR_CODE 0x5000
#define RCM_CLIENT_JOB_BASE_ERROR_CODE    0x5100

namespace RcmClientLib
{
    /// \brief status codes returned by the converter class
    typedef enum RcmClientErrorCodes {
        RCM_CLIENT_EMPTY_URI_ERROR = RCM_CLIENT_MODULE_BASE_ERROR_CODE,
        RCM_CLIENT_EMPTY_BIOSID_ERROR,
        RCM_CLIENT_EMPTY_MANAGEMENTID_ERROR,
        RCM_CLIENT_EMPTY_HOSTID_ERROR,
        RCM_CLIENT_EMPTY_HOSTNAME_ERROR,
        RCM_CLIENT_BIOSID_MISMATCH_ERROR,
        RCM_CLIENT_INVALID_SYSTEMTYPE,
        RCM_CLIENT_DATA_CACHER_ERROR,
        RCM_CLIENT_INVALID_HYPERVISOR_TYPE,
        RCM_CLIENT_EMPTY_AGENT_VERSION_ERROR,
        RCM_CLIENT_EMPTY_DRIVER_VERSION_ERROR,
        RCM_CLIENT_EMPTY_INSTALLPATH_ERROR,
        RCM_CLIENT_POST_FAILED,
        RCM_CLIENT_CAUGHT_EXCEPTION,
        RCM_CLIENT_GET_BEARER_TOKEN_FAILED,
        RCM_CLIENT_CREATE_JWT_FAILED,
        RCM_CLIENT_AAD_AUTH_CERT_NOT_FOUND,
        RCM_CLIENT_PROTECTION_DISABLED,
        RCM_CLIENT_SERVER_CERT_VALIDATION_ERROR,
        RCM_CLIENT_COULDNT_CONNECT,
        RCM_CLIENT_COULDNT_RESOLVE_PROXY,
        RCM_CLIENT_COULDNT_RESOLVE_HOST,
        RCM_CLIENT_PROTECTION_ENABLED,
        RCM_CLIENT_AAD_ERROR_APP_ID_NOT_FOUND,
        RCM_CLIENT_AAD_ERROR_SYSTEM_TIME_OUT_OF_SYNC,
        RCM_CLIENT_ERROR_NETWORK_TIMEOUT,
        RCM_CLIENT_AAD_PRIVATE_KEY_NOT_FOUND,
        RCM_CLIENT_AAD_POST_FAILED,
        RCM_CLIENT_AAD_COULDNT_CONNECT,
        RCM_CLIENT_AAD_COULDNT_RESOLVE_PROXY,
        RCM_CLIENT_AAD_COULDNT_RESOLVE_HOST,
        RCM_CLIENT_SERVER_SSL_CONNECT_ERROR,
        RCM_CLIENT_PROXY_IMPL_LOGIN_AUTH_FAILURE,
        RCM_CLIENT_PROXY_IMPL_LOGIN_FORBIDDEN,
        RCM_CLIENT_PROXY_IMPL_CLOUD_PAIRING_INCOMPLETE,
        RCM_CLIENT_EMPTY_DISTRO_NAME_ERROR,
        RCM_CLIENT_EMPTY_PROTECTION_SCENARIO_ERROR,
        RCM_CLIENT_ERROR_HTTP_RESPONSE_UNKNOWN,
        RCM_CLIENT_REGISTRATION_NOT_SUPPORTED,
        RCM_CLIENT_REGISTRATION_NOT_ALLOWED,
        RCM_CLIENT_EMPTY_RESOURCEID_ERROR,
        RCM_CLIENT_INVALID_ARGUMENT,
        RCM_CLIENT_INVALID_PERSISTED_SOURCE_CONFIG,
        RCM_CLIENT_INVALID_SOURCE_CONFIG_BIOS_ID_OR_FQDN,
        RCM_CLIENT_VAULT_MISMATCH,
        RCM_CLIENT_APPLIANCE_MISMATCH,
        RCM_CLIENT_GET_NON_CACHED_SETTINGS_WARNING,
        RCM_CLIENT_AAD_ERROR_CACHED_TOKEN_INVALID,
        RCM_CLIENT_AAD_ERROR_WITH_HTTP_RESPONSE,
        RCM_CLIENT_HOSTID_NOT_PRESENT_IN_AZURETOAZURE_REPLICATIONESETTINGS,
        RCM_CLIENT_CLUSTERID_NOT_PRESENT_IN_AZURETOAZURE_REPLICATIONESETTINGS,
        RCM_CLIENT_FAILOVER_CLUSTER_PROPERTIES_COLLECTOR_ERROR,
        RCM_CLIENT_INVALID_CLUSTER_SERVICE_STATUS,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_ID,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_NAME,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_TYPE,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_CURRENT_NODE_NAME,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_MANAGEMENT_ID,
        RCM_CLIENT_FAILOVER_CLUSTER_EMPTY_NODE_LIST,
        RCM_CLIENT_CLUSTER_ID_NOT_PRESENT_IN_AZURETOAZURE_REPLICATIONESETTINGS,
        RCM_CLIENT_DIAGNOSE_AND_FIX_FAILED,
        RCM_CLIENT_CLUSTER_FEATURE_SET_FAILED
    } RCM_CLIENT_STATUS;

    typedef enum RcmClientJobErrorCodes {
        RCM_CLIENT_JOB_UNKNOWN_ERROR = RCM_CLIENT_JOB_BASE_ERROR_CODE,
        RCM_CLIENT_JOB_RESYNC_START_NOTIFY_ERROR,
        RCM_CLIENT_JOB_RESYNC_END_NOTIFY_ERROR,
        RCM_CLIENT_JOB_START_TRACKING_ERROR,
        RCM_CLIENT_JOB_END_TRACKING_ERROR,
        RCM_CLIENT_JOB_STOP_FILTERTING_ERROR,
        RCM_CLIENT_JOB_BASELINE_BOOKMARK_ERROR,
        RCM_CLIENT_JOB_DRIVER_NOT_INIT_ERROR,
        RCM_CLIENT_JOB_DEVICE_NOT_FOUND_ERROR,
        RCM_CLIENT_JOB_DEVICE_DETAILS_ADD_ERROR,
        RCM_CLIENT_JOB_DEPRECATED_1_ERROR, // RCM_CLIENT_JOB_DEVICE_DETAILS_SCSI_ID_MISMATCH_ERROR
        RCM_CLIENT_JOB_DRIVER_IOCTL_ERROR,
        RCM_CLIENT_JOB_DRIVER_IOCTL_EXCEPTION,
        RCM_CLIENT_JOB_DEVICE_DETAILS_NOT_FOUND_ERROR,
        RCM_CLIENT_JOB_DEVICE_RESIZE_REPLACE_ERROR,
        RCM_CLIENT_JOB_SETTINGS_PARSE_ERROR,
        RCM_CLIENT_JOB_PREPARE_FOR_SYNC_ERROR,
        RCM_CLIENT_JOB_AGENT_UPGRADE_ERROR,
        RCM_CLIENT_JOB_AGENT_DOWNLOAD_FAILED,
        RCM_CLIENT_JOB_AGENT_EXTRACTION_FAILED,
        RCM_CLIENT_JOB_AGENT_UPGRADE_JOB_SERIALIZATION_FAILED,
        RCM_CLIENT_JOB_AGENT_INSTALLER_PACKAGE_NOT_FOUND,
        RCM_CLIENT_JOB_AGENT_INSTALLER_CHECKSUM_MISMATCH,
        RCM_CLIENT_JOB_FINAL_BOOKMARK_ERROR,
        RCM_CLIENT_JOB_DRIVER_COMMIT_NOTIFY_NOT_SUPPORTED_ERROR,
        RCM_CLIENT_JOB_AGENT_UPGRADE_LOW_ON_FREE_SPACE_ERROR,
        RCM_CLIENT_JOB_PREPARE_FOR_SWITCH_APPLIANCE_ERROR,
        RCM_CLIENT_JOB_SWITCH_APPLIANCE_ERROR,
        RCM_CLIENT_JOB_SWITCH_BACK_TO_CS_STACK_ERROR,
        RCM_CLIENT_JOB_CS_STACK_MACHINE_START_DRAINING_ERROR,
        RCM_CLIENT_JOB_FAILOVER_EXTENDED_LOCATION_ERROR, 
        RCM_CLIENT_JOB_SHARED_DISK_START_TRACKING_ERROR
    } RCM_CLIENT_JOB_ERROR_CODES;

    namespace RCM_ERRORS {
        const std::string IdentityDoesNotExist("IdentityDoesNotExist");
        const std::string MachineDoesNotExist("MachineDoesNotExist");
        const std::string SourceAgentDoesNotExist("SourceAgentDoesNotExist");
        const std::string MachineInUse("MachineInUse");
        const std::string SourceAgentInUse("SourceAgentInUse");

        const std::string StorageAccountNotAvailable("StorageAccountNotAvailable");
        const std::string LogContainerDoesNotExist("LogContainerDoesNotExist");
        const std::string AzureResourceManagerOperationFailed("AzureResourceManagerOperationFailed");

        const std::string AzureToOnPremFreshProtectionIsNotSupported("AzureToOnPremFreshProtectionIsNotSupported");
        const std::string ReprotectWithoutFailoverIsNotsupported("ReprotectWithoutFailoverIsNotsupported");

        const std::string RegistrationNotAllowed("RegistrationNotAllowed");

        const std::string ApplianceMismatchForSourceMachineRequest("ApplianceMismatchForSourceMachineRequest");
    }

    namespace RCM_PROXY_ERRORS {
        const std::string RcmProxyNotConnectedToRcm("RcmProxyNotConnectedToRcm");
    }
}
#endif
