include top.mak

SRCS =  svconfig.cpp

X_CFLAGS = \
	-DLINUX_OS \
	-Icommon	\
	-Ifr_common \
	-Ifr_common/$(X_MAJOR_ARCH) \
	-Iinmsafecapis \
	-Iinmsafecapis/$(X_MAJOR_ARCH) \

X_LIBS = 

X_THIRDPARTY_LIBS = 

X_SYSTEM_LIBS =

X_LDFLAGS =

BINARY=$(X_LIBPRE)fr_config
BINARY_EXT=$(X_LIBEXT)

include bottom.mak

