include top.mak

SRCS = \
	$(X_MAJOR_ARCH)/utildirbasename.cpp \

X_CFLAGS = \
	-Idirbasename \
	-Idirbasename/$(X_MAJOR_ARCH) \

X_LIBS = 

X_THIRDPARTY_LIBS = 

X_SYSTEM_LIBS =

X_LDFLAGS =

BINARY=$(X_LIBPRE)dirbasename
BINARY_EXT=$(X_LIBEXT)

include bottom.mak
