include top.mak

SRCS = \
	platforminfo.cpp \
	$(X_MINOR_ARCH)/specificplatforminfo.cpp \


X_CFLAGS = \
	-Iplatforminfo/$(X_MINOR_ARCH) \
	-Iplatforminfo \

X_LIBS = 

X_THIRDPARTY_LIBS = 

X_SYSTEM_LIBS =

X_LDFLAGS =

BINARY=$(X_LIBPRE)platforminfo
BINARY_EXT=$(X_LIBEXT)

include bottom.mak
