#ifndef FS_SUPPORT_ACTIONS_H
#define FS_SUPPORT_ACTIONS_H

typedef enum eFsSupportActions
{
    E_SET_NO_CAPABILITIES_IFNOSUPPORT,
    E_SET_NOFS_CAPABILITIES_IFNOSUPPORT,
	E_SET_NOFS_CAPABILITIES

} E_FS_SUPPORT_ACTIONS;

#endif /* FS_SUPPORT_ACTIONS_H */
