#define COMPANY "InMage"
#define COMPANYNAME "InMage Systems"
#define PRODUCT ""
#define REGISTRYNAME "SV Systems"
#define HOMENAME "svsystems"
#define OSTYPE "win"
#define URL "http://www.inmage.com"
#define INSTALLPATH "Microsoft Azure Site Recovery"
#define USERMANUAL "DR-Scout_UserManual.pdf"
