#define INMAGE_PRODUCT_VERSION_STR "DAILY_8.2.0.0_DIT_3672_Jan_20_2015"
#define INMAGE_PRODUCT_VERSION 8,2,3672,1
#define INMAGE_PRODUCT_VERSION_MAJOR 8
#define INMAGE_PRODUCT_VERSION_MINOR 2
#define INMAGE_PRODUCT_VERSION_BUILDNUM 3672
#define INMAGE_PRODUCT_VERSION_PRIVATE 1
#define INMAGE_HOST_AGENT_CONFIG_CAPTION "DAILY_8.2.0.0_DIT_3672_Jan_20_2015"
#define PROD_VERSION "8.2.0.0"
#define INMAGE_COPY_RIGHT "(C) 2015 Microsoft Corp. All rights reserved."
#define INMAGE_PRODUCT_NAME "Microsoft Azure Site Recovery"
