#include <tchar.h>
#include <Windows.h>

extern const int ERROR_USE_PROPER_COMMANDLINE_ARGS;
extern const int ERROR_NULL_PROCESS_NAME_GIVEN_TO_SPAWN;
extern const int ERROR_COULD_NOT_REGISTER_SERVICE_CTRL_HANDLER;
extern const int ERROR_NULL_PROCESS_NAME_GIVEN_TO_SPAWN;

extern LPSTR CX_SERVICE_NAME;
extern LPSTR CX_SERVICE_DISPLAY_NAME;
extern LPSTR CX_SERVICE_DESCRIPTION;
