<?php
	ob_start();
	
	include("xmlrpc.inc");
	include("xmlrpcs.inc");
	include("xmlrpc_wrappers.inc");
	include("method_definition.php");

	/* Remove buffer content */
	$buffer_contents = trim(ob_get_contents());
	ob_end_clean();

	/**
	* Used to test usage of object methods in dispatch maps
	*/
	class xmlrpc_server_methods_container
	{
		/*
		* Method used to test logging of php warnings generated by user functions.
		*/
		function phpwarninggenerator($m)
		{
			$a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
			return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
		}
	}

	$o = new xmlrpc_server_methods_container;

	$s = new xmlrpc_server($a, false);
	$s->setdebug(3);
	$s->compress_response = true;

	// out-of-band information: let the client manipulate the server operations.
	// we do this to help the testsuite script: do not reproduce in production!
	if (isset($_GET['RESPONSE_ENCODING']))
		$s->response_charset_encoding = $_GET['RESPONSE_ENCODING'];

	$s->service();
?>