<?php
class ErrorCodes{
	const EC_SUCCESS = 0;
	const EC_INVALID_FORMAT = -1;
	const EC_AUTH_FAILURE = -2;
	const EC_ATHRZTN_FAILURE = -3;
	const EC_FUNC_NOT_SUPPORTED = -4;
	const EC_INTERNAL_SERVER_ERROR = -5;
	const EC_UNKNWN = -6;
	const EC_ACCESSKEY_NOT_FOUND = -7;
	const EC_INVLD_AUTH_MTHD = -8;
	const EC_USRNME_NOT_FOUND = -9;
	const EC_PASSWD_NOT_FOUND = -10;
	const EC_PASSPHRASE_EMPTY = -11;
	const EC_FINGERPRINT_EMPTY = -12;
	const EC_INSFFCNT_PRMTRS = 1;
	const EC_WRNG_PRMTR_TYPE = 2;
	const EC_NO_DATA = 3;
	const EC_MTAL_EXCLSIVE_ARGS = 4;
	const EC_REQUEST_IN_PROCESS = 5;
	
	//RepositoryHandler Error codes
	const EC_NO_RPSTRY_CNFGRD = 202;
	const EC_NO_RPSTRY_FND = 203;
	const EC_RPSTRY_NME_ALRDY_FND = 204;
	const EC_STRGE_PTH_NOT_FND = 205;
	const EC_DEVICE_TYP_MISMTCH = 209;
	const EC_REPSITRY_NT_CNFD_FOR_SYS = 207;
	const EC_DEVICE_ALRDY_EXPRTD_THRGH_CIFS = 210;
	const EC_DEVICE_NOT_EXPRTD_THRGH_CIFS = 211;
	const EC_UNEXPORT_PENDING_FOR_DEVICE = 212;
	const EC_DEVICE_NT_ELGBLE_FOR_REPSITRY = 213;
	const EC_DEVICE_NT_REDY_FOR_EXPORT = 216;
	
	//ProtectionHandler Error codes
	const EC_NO_HST_FND_WTH_SYSTM_GUID = 16;
	const EC_HST_NOT_UNDR_PRTECTION = 17;
	const EC_HST_ALRADY_UNDR_PRTECTION = 12;
	const EC_BOOT_VOL_CANT_BE_EXCLDED = 102;
	const EC_REPSITRY_VOL_NOT_HVE_SUFFICENT_SPCE = 201;
	const EC_NO_REPSITRY_FND_WITH_NME = 206;
	const EC_EXCLD_VOL_NOT_FND = 108;
	const EC_VOL_IS_ALRDY_PROTED = 119;
	const EC_VOL_NOT_IN_RIGT_STE = 120;
	const EC_PAIRS_IN_RESYNC = 406;
	
	const EC_NO_AGENTS = 11;
	
	const EC_NO_PROTECTION = 501;
	const EC_VOLPACK_CREATION_PENDING  = 509;
	const EC_VOLPACK_CREATION_FAILED = 508;
	const EC_SCENARIO_DELETION_PENDING = 510;
	const EC_SCENARIO_DELETION_FAILED = 511;
	
	const EC_VOL_NOT_OUT_OF_SYNC = 122;
	const EC_VOL_ABT_TO_RESYNCED = 123;
	const EC_RESYNC_REQUIRED_SET = 124;
	const EC_PAIRS_IN_INITIAL_STATE = 125;
	
	const EC_DELETE_INPROGRESS = 503;
	
	const EC_NO_METADATA = 301;
	
	const EC_RESTART_RESYNC_FAILED = 504;
	
	const EC_LUNS_ALREADY_PAUSED = 551;
	const EC_LUNS_PAUSE_FAILED = 552;
	const EC_LUNS_NOT_PAUSED = 553;
	const EC_RESUME_FAILED = 554;
	const EC_PAUSE_PENDING = 555;
	const EC_PAUSE_PROGRESS = 556;
	const EC_RUSME_PENDING = 557;
	const EC_RESUME_IN_PROGRESS = 558;
	
	
	

	const EC_DUP_SYSTEMID = 21;
	const EC_DUP_HOSTNAME = 18;
	const EC_DUP_HOSTIP = 19;
	const EC_DUP_MACADDR = 20;
	const EC_NO_HOSTS = 15;
	const EC_NO_HOSTS_NAME = 13;
	const EC_NO_HOSTS_IP = 14;
	const EC_NO_HOSTS_MAC = 22;
	const EC_NO_VOLUMES = 114;
	const EC_PROTECTION_INTACT = 103;
	const EC_UPDATE_PROTECTION_FAILED = 120;
	const EC_VOLUME_NOT_PROTECTED = 105;
	const EC_NO_VOLUME_NAME = 104;
	const EC_PROTECTION_DIF = 118;
	const EC_SYS_ALREADY_PAUSED = 506;
	const EC_SYSTEM_INTACT = 505;
	const EC_VOL_ALREADY_PAUSED = 109;
	const EC_VOL_INTACT = 103;
	const EC_VOL_ALREADY_PAUSED_TRACKED = 121;

    //RecoveryHandler Error codes
    const EC_NO_RESTORE_PTS_AVAILABLE = 401;   
	
	const EC_INVLD_INFRMTNTYP = 2301;
	const EC_NO_MBR_AVLBLE = 2302;
	const EC_NO_RQUSTID_FOND = 2303;	
	const EC_PAIRS_IN_QUEUED_STATE = 2304;	
    const EC_NO_PLNID_FOND = 2401;
	const EC_PLNNAME_EXSTS = 2402;
	
    const EC_NO_LUN_PROTECTED = 559;
    const EC_NO_AXIOM_REGD = 1052;
    const EC_NO_ARRAY_FOUND = 1053;
    const EC_NO_MASTER_NODE_FOUND = 1054;
	const EC_SAME_IP = 2501;
	const EC_NO_BUILD_FOUND = 2502;
	const EC_PUSH_SERVER_NOT_EXISTS = 2503;
	const EC_MISSING_PRMTR_GROUP = 2504;

	//SchedulerHandler Error codes
	const EC_CONNECTION_ERROR = 3001;
	const EC_EXECUTION_ERROR = 3002;
	const EC_TRANSACTION_ERROR = 3003;
   	const EC_INVLD_DATA_PRMTR_TYPE = 3006;
   	
   	const EC_SAME_INSTALL_IP = 3011;
   	const EC_NO_PUSH_SERVER = 3012;
	const EC_NO_PUSH_CLIENT = 3013;
	const EC_NO_BUILD = 3014;	
	
	const EC_NO_INSTALLATION = 3016;
	
	const EC_NO_TARGET_VOLUMES = 3032;
	const EC_NO_PAIRS = 3047;
	const EC_NO_RETENTION_VOLUMES = 3033;
	const EC_NO_SUFFICIENT_SPACE_FOR_RETENTION = 3034;	
	const EC_TARGET_SIZE_CHECK = 3035;
	const EC_PROTECTION_EXIST = 3036;
	const EC_OS_CHECK = 3037;
	const EC_IS_SOURCE_VOLUME_ELIGIBLE = 3038;
	const EC_IS_TARGET_VOLUME_ELIGIBLE = 3039;
	const EC_VOLUME_CHECK = 3040;
		
	const EC_NO_CONSISTENCY = 3064;
	const EC_ROLLBACK_EXISTS = 3065;
	
	const EC_NO_ROLLBACK_POLICIES = 3077;
	
	const EC_NO_AGENT_INSTALLATION = 3106;
	const EC_SAME_AGENT_UNINSTALL = 3107;
	
	const EC_NO_UNINSTALLATION = 3121;

	//ASR Handler Error codes
	const EC_NO_RECORD_INFO = 'ECA0004';	
	const EC_NO_AGENT_FOUND = 'ECA0104';
	const EC_NO_MT_FOUND = 'ECA0105';
	const EC_NO_PS_FOUND = 'ECA0106';
	const EC_NO_HOST_FOUND = 'ECA0152';
	const EC_PASSPHRASE_READ_FAILED = 'ECA0177';
	const EC_SIGNATURE_PASSWORD_MISMATCH = 'ECA0178';
	const EC_ACCESS_KEY_NOT_FOUND = 'ECA0179';
	const EC_FINGERPRINT_READ_FAILED = 'ECA0180';
	const EC_INVALID_AUTHENTICATION_METHOD = 'ECA0181';
	
}
?>