#ifndef __INSTALL_CLUSTER_DISK_FILTER_H__
#define  __INSTALL_CLUSTER_DISK_FILTER_H__

#include <tchar.h>
#include <windows.h>

//Used TCHAR_ARRAY_SIZE to get exact size of array in case of TCHAR/WCHAR/CHAR array cases.
#if !defined(TCHAR_ARRAY_SIZE)
#define TCHAR_ARRAY_SIZE( a ) ( sizeof( a ) / sizeof( a[ 0 ] ) )
#endif

#define IS_DRIVE_LETTER(x)      ((('A' <= (x)) && ('Z' >= (x))) || (('a' <= (x)) && ('z' >= (x))))

typedef enum _CDSK_INSTALL_STATUS
{
    CDSK_INSTALL_SUCCESS = 0,
    CDSK_INSTALL_EXPAND_ENV_STRING_FAILED = 1,
    CDSK_INSTALL_MEMORY_ALLOC_FAILED = 2,
    CDSK_INSTALL_EXPAND_ENV_STRING_RETRY_LIMIT_REACHED = 3,
    CDSK_INSTALL_OPEN_FILE_FAILED = 4,
    CDSK_INSTALL_OPEN_SCMANAGER_FAILED = 5,
    CDSK_INSTALL_DRIVER_DOES_NOT_EXIST = 6,
    CDSK_INSTALL_OPEN_SERVICE_FAILED = 7,
    CDSK_INSTALL_QUERY_SERVICE_STATUS_FAILED = 8,
    CDSK_INSTALL_DRIVER_STATUS_IS_STOPPED = 9,
    CDSK_INSTALL_DRIVER_STATUS_IS_RUNNING = 10,
    CDSK_INSTALL_REG_OPEN_KEY_EX_FAILED = 11,
    CDSK_INSTALL_REG_QUERY_VALUE_EX_FAILED = 12,
    CDSK_INSTALL_FAILED_TO_GET_TAG_OF_CLUSDISK = 13,
    CDSK_INSTALL_NUM_TAGS_AND_SIZE_MISMATCH = 14,
    CDSK_INSTALL_CLUSDISK_TAG_NOT_FOUND_IN_GROUP = 15,
    CDSK_INSTALL_REG_SET_VALUE_EX_FAILED = 16,
    CDSK_INSTALL_CREATE_SERVICE_FAILED = 17,
    CDSK_INSTALL_REG_DELETE_KEY_FAILED = 18,
    CDSK_INSTALL_CLUSDISK_NOT_INSTALLED = 19,
    CDSK_INSTALL_IMAGEPATH_VALUE_CREATE_FAILED = 20,
    CDSK_INSTALL_GROUP_VALUE_CREATE_FAILED = 21,
    CDSK_INSTALL_MAX_ERROR_VALUE = 22,
} CDSK_INSTALL_STATUS, *PCDSK_INSTALL_STATUS;

extern DWORD dwWin32Error;
extern TCHAR *ErrorDescriptions[CDSK_INSTALL_MAX_ERROR_VALUE + 1];


CDSK_INSTALL_STATUS
InstallInMageClusDiskFilterDriver(
    TCHAR       *DriverName,
    TCHAR       *DisplayName,
    TCHAR       *Filepath
    );

CDSK_INSTALL_STATUS
DeleteDriverKeys(LPTSTR DriverName);

TCHAR *
GetCDskInstallErrorDescription(ULONG ulErrorNum);

#endif //  __INSTALL_CLUSTER_DISK_FILTER_H__