
// <copyright file="MarsAgentException.codegen.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// <autogenerated />

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;

namespace MarsAgent.ErrorHandling
{
    public partial class MarsAgentException
    {
        public static Dictionary<MarsAgentErrorCode, string> ErrorCodeToSeverityDict = 
            new Dictionary<MarsAgentErrorCode, string>()
        {
            {MarsAgentErrorCode.UnhandledException, "Error"},
            {MarsAgentErrorCode.RcmOperationFailed, "Error"},
            {MarsAgentErrorCode.RcmAgentOperationFailed, "Error"},
            {MarsAgentErrorCode.MarsAgentConfigurationValidationFailed, "Error"},
            {MarsAgentErrorCode.ServicesNotRunning, "Error"},
            {MarsAgentErrorCode.ServicesNotInstalled, "Error"},
            {MarsAgentErrorCode.ServiceIsInDisabledState, "Error"},
        };

        public static Dictionary<MarsAgentErrorCode, Dictionary<string, string>> ErrorCodeToTagsDict =
            new Dictionary<MarsAgentErrorCode, Dictionary<string, string>>()
            {
                {
                    MarsAgentErrorCode.UnhandledException,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.RcmOperationFailed,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.RcmAgentOperationFailed,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.MarsAgentConfigurationValidationFailed,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.ServicesNotRunning,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.ServicesNotInstalled,
                    new Dictionary<string, string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.ServiceIsInDisabledState,
                    new Dictionary<string, string>()
                    {
                    }
                },
            };

        public static Dictionary<MarsAgentErrorCode, List<string>> ErrorCodeToMessageParamsDict =
            new Dictionary<MarsAgentErrorCode, List<string>>()
            {
                {
                    MarsAgentErrorCode.UnhandledException,
                    new List<string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.RcmOperationFailed,
                    new List<string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.RcmAgentOperationFailed,
                    new List<string>()
                    {
                    }
                },
                {
                    MarsAgentErrorCode.MarsAgentConfigurationValidationFailed,
                    new List<string>()
                    {
                        "ComponentServiceName",
                        "ErrorLabel",
                        "ErrorCodeName",
                    }
                },
                {
                    MarsAgentErrorCode.ServicesNotRunning,
                    new List<string>()
                    {
                        "Service",
                    }
                },
                {
                    MarsAgentErrorCode.ServicesNotInstalled,
                    new List<string>()
                    {
                        "Service",
                    }
                },
                {
                    MarsAgentErrorCode.ServiceIsInDisabledState,
                    new List<string>()
                    {
                        "Service",
                        "ServiceName",
                    }
                },
            };

        public static System.Collections.Generic.Dictionary<MarsAgentErrorCode, System.Net.HttpStatusCode> ErrorCodeToHttpStatusCode =
            new System.Collections.Generic.Dictionary<MarsAgentErrorCode, System.Net.HttpStatusCode>()
            {
            };
        public static MarsAgentException UnhandledException()
        {
             return new MarsAgentException(
                MarsAgentErrorCode.UnhandledException,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                });
        }
        public static MarsAgentException RcmOperationFailed()
        {
             return new MarsAgentException(
                MarsAgentErrorCode.RcmOperationFailed,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                });
        }
        public static MarsAgentException RcmAgentOperationFailed()
        {
             return new MarsAgentException(
                MarsAgentErrorCode.RcmAgentOperationFailed,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                });
        }
        public static MarsAgentException MarsAgentConfigurationValidationFailed(string componentServiceName, string errorLabel, string errorCodeName)
        {
             return new MarsAgentException(
                MarsAgentErrorCode.MarsAgentConfigurationValidationFailed,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                    {"ComponentServiceName", componentServiceName },
                    {"ErrorLabel", errorLabel },
                    {"ErrorCodeName", errorCodeName },
                });
        }
        public static MarsAgentException ServicesNotRunning(string service)
        {
             return new MarsAgentException(
                MarsAgentErrorCode.ServicesNotRunning,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                    {"Service", service },
                });
        }
        public static MarsAgentException ServicesNotInstalled(string service)
        {
             return new MarsAgentException(
                MarsAgentErrorCode.ServicesNotInstalled,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                    {"Service", service },
                });
        }
        public static MarsAgentException ServiceIsInDisabledState(string service, string serviceName)
        {
             return new MarsAgentException(
                MarsAgentErrorCode.ServiceIsInDisabledState,
                new System.Collections.Generic.Dictionary<string, string>()
                {
                    {"Service", service },
                    {"ServiceName", serviceName },
                });
        }
    }
}
