
// <copyright file="MarsAgentErrorCode.codegen.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// <autogenerated />

#pragma warning disable 1591
namespace MarsAgent.ErrorHandling
{
    public enum MarsAgentErrorCode
    {
        UnhandledException = 7500,
        RcmOperationFailed = 7501,
        RcmAgentOperationFailed = 7502,
        MarsAgentConfigurationValidationFailed = 7503,
        ServicesNotRunning = 7504,
        ServicesNotInstalled = 7505,
        ServiceIsInDisabledState = 7506,
    }
}
#pragma warning restore
