// service.idl : IDL source for service.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (service.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    uuid(EB09A37C-F819-4EA8-8556-4ECF116EB1D5),
    version(1.0),
    helpstring("service 1.0 Type Library")
]
library SERVICELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

};
