include top.mak

SRCS = \
        main.cpp \
	inmzpool.cpp \
	inmcommand.cpp \

X_CFLAGS = \
        -Wcast-align \
	-Iinmzpool \
	$(ACE_INCLUDE) \
	$(BOOST_INCLUDE) \

X_LIBS =

X_THIRDPARTY_LIBS = \
	$(ACE_LIBS) \

X_SYSTEM_LIBS = 

X_LDFLAGS =

BINARY=inmzpool
BINARY_EXT=$(X_EXEEXT)

include bottom.mak
