//---------------------------------------------------------------
//  <copyright file="VMwareClientException.cs" company="Microsoft">
//      Copyright (c) Microsoft Corporation. All rights reserved.
//  </copyright>
//
//  <summary>
//  Exception class to represent all the errors generated by InMageVMware.
//  </summary>
//
//  History:     05-May-2015   GSinha   Created
//----------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Text;
using System.Text.RegularExpressions;

namespace VMware.Client
{
    /// <summary>
    /// Enumeration describing the severity level of the error.
    /// </summary>
    public enum Severity
    {
        /// <summary>
        /// Default - unused.
        /// </summary>
        NONE = 0,

        /// <summary>
        /// Informational message.
        /// </summary>
        Info,

        /// <summary>
        /// Warning message.
        /// </summary>
        Warning,

        /// <summary>
        /// Error message.
        /// </summary>
        Error
    }

    /// <summary>
    /// Exceptions thrown within the InMageVMware wrapper to capture errors that need to be sent
    /// to DRA.
    /// </summary>
    public partial class VMwareClientException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VMwareClientException"/> class.
        /// </summary>
        /// <param name="errorCode">The error code to be associated with the exception.</param>
        /// <param name="errorMsgParams">Parameters required to construct the error message.
        /// </param>
        public VMwareClientException(
            VMwareClientErrorCode errorCode, 
            Dictionary<string, string> errorMsgParams)
        {
            this.ErrorCode = errorCode;
            this.MessageParameters = errorMsgParams;
            this.Data.Add("ErrorCode", this.ErrorCode);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VMwareClientException"/> class.
        /// This constructor is used to create an instance of <see cref="VMwareClientException"/>
        /// with an inner exception.
        /// </summary>
        /// <param name="exception">Instance of <see cref="VMwareClientException"/> from which this
        /// exception is to be initialized.</param>
        /// <param name="innerException">Inner exception to be associated with this instance.
        /// </param>
        public VMwareClientException(
            VMwareClientException exception,
            Exception innerException) : base(exception.Message, innerException)
        {
            this.ErrorCode = exception.ErrorCode;
            this.MessageParameters = exception.MessageParameters;
            this.Data.Add("ErrorCode", this.ErrorCode);
        }

        /// <summary>
        /// Enumeration used to determine the relevant resource string ID for a given error from
        /// the resource file.
        /// </summary>
        private enum ResourceType
        {
            /// <summary>
            /// The message associated with the error.
            /// </summary>
            Message,

            /// <summary>
            /// The possible causes for the error.
            /// </summary>
            PossibleCauses,

            /// <summary>
            /// The recommended action for resolving the error.
            /// </summary>
            RecommendedAction
        }

        /// <summary>
        /// Gets the error code associated with the exception.
        /// </summary>
        public VMwareClientErrorCode ErrorCode { get; private set; }

        /// <summary>
        /// Gets the message parameters needed to form the error message.
        /// </summary>
        public Dictionary<string, string> MessageParameters { get; private set; }

        /// <summary>
        /// Creates the error message. Use GetErrorMessage if you want to specify culture.
        /// </summary>
        public override string Message
        {
            get
            {
                return this.GetErrorMessage(CultureInfo.InstalledUICulture.Name);
            }
        }

        /// <summary>
        /// Get the error message defined for the error in the specified culture.
        /// </summary>
        /// <param name="culture">The specific culture in which the message is needed.</param>
        /// <returns>The error message defined for the error.</returns>
        public string GetErrorMessage(string culture)
        {
            string messageResourceId = GetResourceId(this.ErrorCode, ResourceType.Message);
            return MessageFormatter.GetFormattedMessageString(
                messageResourceId,
                this.MessageParameters,
                culture);
        }

        /// <summary>
        /// Get the possible causes defined for the error in the specified culture.
        /// </summary>
        /// <param name="culture">The specific culture in which the message is needed.</param>
        /// <returns>The possible causes defined for the error.</returns>
        public string GetPossibleCauses(string culture)
        {
            string messageResourceId = GetResourceId(this.ErrorCode, ResourceType.PossibleCauses);
            return MessageFormatter.GetFormattedMessageString(
                messageResourceId,
                this.MessageParameters,
                culture);
        }

        /// <summary>
        /// Get the recommended action defined for the error in the specified culture.
        /// </summary>
        /// <param name="culture">The specific culture in which the message is needed.</param>
        /// <returns>The recommended action defined for the error.</returns>
        public string GetRecommendedAction(string culture)
        {
            string messageResourceId =
                GetResourceId(this.ErrorCode, ResourceType.RecommendedAction);
            return MessageFormatter.GetFormattedMessageString(
                messageResourceId,
                this.MessageParameters,
                culture);
        }

        /// <summary>
        /// Get the resource Id used in the resource file.
        /// </summary>
        /// <param name="errorCode">The error code whose resource id is needed.</param>
        /// <param name="errorResourceType">The resource type whose resource id is needed.</param>
        /// <returns>The resource Id used in the resource file.</returns>
        private static string GetResourceId(
            VMwareClientErrorCode errorCode,
            ResourceType errorResourceType)
        {
            switch (errorResourceType)
            {
                case ResourceType.Message:
                    return string.Format("Error_{0}_Message", (int)errorCode);
                case ResourceType.PossibleCauses:
                    return string.Format("Error_{0}_Causes", (int)errorCode);
                case ResourceType.RecommendedAction:
                    return string.Format("Error_{0}_Action", (int)errorCode);
                default:
                    return null;
            }
        }

        /// <summary>
        /// Message formatter class for creating messages in the requested culture.
        /// </summary>
        /// <remarks>This is a copy of the class by the same name from
        /// rec_imp2\Online\RecSrv\SRS\Service\Common\ErrorHandling\MessageFormatter.cs with a few
        /// tweaks for convenience. I am not keen on adding a dependency on ErrorHandling.dll for
        /// InMageVMware - hence the copy.</remarks>
        private class MessageFormatter
        {
            /// <summary>
            /// If a message parameter is not passed, it will be replaced with this string.
            /// </summary>
            private const string NoParameterMarker = "";

            /// <summary>
            /// For having a % character in the message, its better to use %% in the message.
            /// The %% in the message is replaced with this for safe parsing, and replaced back
            /// with %.
            /// </summary>
            private const string ANSIIMarkerForPercent = "&#37;";

            /// <summary>
            /// Regular expression for matching parameter names (e.g. %PrimaryCloudName;) in the
            /// message.
            /// </summary>
            private static readonly Regex ParameterRegex = new Regex(
                @"%[^%]*?;",
                RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);

            /// <summary>
            /// Resource manager instance for fetching the messages from the resource file.
            /// </summary>
            private static ResourceManager resourceManager;

            /// <summary>
            /// Initializes static members of the <see cref="MessageFormatter"/> class.
            /// </summary>
            static MessageFormatter()
            {
                resourceManager =
                    new ResourceManager(
                        "VimClient.Resources.VMwareClientErrors",
                        typeof(VMwareClientException).Assembly);
            }

            /// <summary>
            /// Formats and returns the message string in the given locale.
            /// </summary>
            /// <param name="resourceId">The resource id.</param>
            /// <param name="parameters">Collection of named parameters for creating message.
            /// </param>
            /// <param name="culture">The culture, in which the string is needed.</param>
            /// <returns>
            /// Formatted message in the given locale. Empty string if resource not found.
            /// </returns>
            public static string GetFormattedMessageString(
                string resourceId,
                IDictionary<string, string> parameters,
                string culture)
            {
                string formatString = GetResourceString(resourceId, culture);
                return FormatString(formatString, parameters);
            }

            /// <summary>
            /// Get resource string for the specified resource id. Empty string if resource is
            /// not found.
            /// </summary>
            /// <param name="resourceId">The resource id.</param>
            /// <param name="culture">The culture, in which the string is needed.</param>
            /// <returns>Resource string in the given locale. Null if resource not found.
            /// </returns>
            private static string GetResourceString(
                string resourceId,
                string culture)
            {
                CultureInfo cultureInfo = new CultureInfo(culture ?? string.Empty);
                return resourceManager.GetString(resourceId, cultureInfo);
            }

            /// <summary>
            /// Replace all the message parameters with that in the list of parameters passed.
            /// </summary>
            /// <param name="formatString">The formatted message in which the values need to be 
            /// replaced.</param>
            /// <param name="parameters">A key value pair of message parameters and values.</param>
            /// <returns>The string with all the parameters replaced.</returns>
            private static string FormatString(
                string formatString, 
                IDictionary<string, string> parameters)
            {
                if (string.IsNullOrWhiteSpace(formatString)) 
                {
                    return string.Empty; 
                }

                StringBuilder sb = new StringBuilder();

                sb.Append(formatString);

                // hide percentage escape characters using their ANSI marker
                sb.Replace("%%", ANSIIMarkerForPercent);

                foreach (Match param in MessageFormatter.ParameterRegex.Matches(formatString))
                {
                    string key = param.Value.Substring(1, param.Length - 2);
                    string parameter;
                    if (parameters == null || !parameters.TryGetValue(key, out parameter))
                    {
                        parameter = MessageFormatter.NoParameterMarker;
                    }

                    sb.Replace(param.Value, parameter);
                }

                sb.Replace(ANSIIMarkerForPercent, "%");

                return sb.ToString();
            }
        }
    }
}
