include top.mak

SRCS = \
	$(X_MAJOR_ARCH)/executecommand.cpp \


X_CFLAGS = \
	-Iexecutecommand \
	-Iexecutecommand/$(X_MAJOR_ARCH) \
    -Icommon \
    -Iinmsafeint \
    -Iinmsafeint/$(X_MAJOR_ARCH) \
    -Icommon/$(X_MAJOR_ARCH) \
    -Iconfig \
    -Ilog \
	$(BOOST_INCLUDE)

X_LIBS = 

X_THIRDPARTY_LIBS = 

X_SYSTEM_LIBS =

X_LDFLAGS =

BINARY=$(X_LIBPRE)executecommand
BINARY_EXT=$(X_LIBEXT)

include bottom.mak
