#ifndef FILECONFIGURATORDEFS_H
#define FILECONFIGURATORDEFS_H

#define PROFILE_DIFFERENTIAL_RATE_OPTION_NO "No"
#define PROFILE_DIFFERENTIAL_RATE_OPTION_YES "Yes"
#define PROFILE_DIFFERENTIAL_RATE_OPTION_WITH_COMPRESSION "WithCompression"

#endif /* FILECONFIGURATORDEFS_H */
