#ifndef INM_NOTICE_ALERT_NUMBERS_H
#define INM_NOTICE_ALERT_NUMBERS_H

typedef enum eInmNoticeAlertNumbers
{
    E_RETENTION_DISK_USAGE_ALERT = 301,
    E_VSNAP_UNMOUNT_ON_PRUNE_ALERT,
    E_VSNAP_UNMOUNT_ALERT,
    E_VSNAP_UNMOUNT_ON_COALESCE_ALERT,
    E_RETENTION_DIR_LOW_SPACE_ALERT,
    E_RETENTION_DIR_FREED_UP_ALERT,
    E_VSNAP_DELETE_ALERT,
    E_RETENTION_PURGED_ALERT
   
} E_INM_NOTICE_ALERT_NUMBER;

#endif /* INM_NOTICE_ALERT_NUMBERS_H */
