<?php
define("HELP_MONITOR", 1);
define("HELP_MONITOR_APP", 2);
define("HELP_MONITOR_VOLUME", 3);
define("HELP_MONITOR_FILE", 0);
define("HELP_MONITOR_SNAPSHOT", 5);
define("HELP_MONITOR_HEARTBEAT", 6);
define("HELP_MONITOR_VERSION", 7);
define("HELP_DATA_CHANGE_RATES", 8);
define("HELP_NETWORK_TRAFFIC_RATES", 9);
define("HELP_BANDWIDTH_REPORT", 10);
define("HELP_HEALTH_REPORT", 11);
define("HELP_HOSTLOGS", 12);
define("HELP_REPLICATION_ENGINE_LOGS", 13);
define("HELP_DOWNLOADLOGS", 14);
define("HELP_AUDITLOGS", 15);
define("HELP_PROTECT", 16);
define("HELP_VIEWAXIOM", 17);
define("HELP_CREATE_PROTECTION_PLAN", 18);
define("HELP_MANAGE_PROTECTION_PLAN", 19);
define("HELP_MANAGE_USERS", 20);
define("HELP_REGISTER_AXIOM", 21);
define("HELP_MANAGE_AXIOM", 22);
define("HELP_RESETTINGS", 23);
define("HELP_AGENT_SETTINGS", 24);
define("HELP_LICENSE_MANAGEMENT", 25);
define("HELP_LOG_MANAGEMENT", 26);
define("HELP_PORT_CONFIGURATION", 27);
define("HELP_SETUP_PROFILING", 28);
define("HELP_ANALYZER_TOOL", 29);
define("HELP_BANDWIDTH_USAGE", 30);
define("HELP_CREATE_BACKUP_SCENARIO", 31);
define("HELP_CREATE_ROLLBACK_SCENARIO", 32);
define("HELP_MANAGE_BACKUP_SCENARIO", 33);
define("HELP_CREAT_RECOVERY_SNAPSHOT", 34);
define("HELP_CREAT_SCHEDULE_SNAPSHOT", 35);
define("HELP_SECONDARY_VOLUME_ROLLBACK", 36);
define("HELP_MONITOR_SNAPSHOT_ROLLBACK", 37);
define("HELP_RECOVER", 38);
define("HELP_REPLICATION_ENGINE_HA", 39);
define("HELP_REMOTE_REPLICATION_ENGINE", 40);


define("HELP_SETTINGS", 41);
define("HELP_MANAGE_AGENT_INSTALLATION_UPGRADE", 100);
define("HELP_SOFTWARE_REPOSITORY", 100);
define("HELP_PROCESS_ENGINE_TRAFFIC_LOAD", 516);
define("HELP_PROCESS_ENGINE_FAILOVER", 100);
define("HELP_RX_SETTINGS", 100);
define("HELP_LDAP_SETTINGS", 100);

?>
