#!/bin/sh

# This is for SLES systems
### BEGIN INIT INFO
# Provides: VolumeReplicationInitAgentService
# Required-Start: network
# Required-Stop:
# Default-Start: 1 2 3 5
# Default-Stop:
# Description:   This script is the daemon script for volume replication agent
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
# copy the script into rc.d location

success_status=0
err() {
	if [ $? -ne 0 ]
	then
		success_status=1
		echo $1 "...failed"
		exit
	else
		echo $1 "...success " 
	fi
}

if [ `id -u` -ne 0 ]
then
	echo "Only root user can install..."
fi

cp inmaged /etc/rc.d/init.d/inmaged
err "copying inmaged script"
cd ../shutdownt
make -s clean
make -s
err "Building notify_sys_shutdown exe"
cp notify_sys_shutdown /etc/rc.d/init.d/
err "Copying notify_sys_shutdown"
cd ../shutdown_script
#echo "creating symbolic links for start and stop"
#shutdown time K scripts
rm -f /etc/rc.d/rc6.d/K93inmaged
rm -f /etc/rc.d/rc0.d/K93inmaged
rm -f /etc/rc.d/rc2.d/K93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc6.d/K93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc0.d/K93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc2.d/K93inmaged

# startup scripts
rm -f /etc/rc.d/rc5.d/S93inmaged
rm -f /etc/rc.d/rc2.d/S93inmaged
rm -f /etc/rc.d/rc3.d/S93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc5.d/S93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc2.d/S93inmaged
ln -s /etc/rc.d/init.d/inmaged /etc/rc.d/rc3.d/S93inmaged

err "creating symbolic links"

if [ $success_status -eq 0 ]
then
	echo "Installation of shutdown script & exe .. Successful"
else
	echo "Installation of shutdown script & exe .. Failed"
fi
