<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * BPMPolicies Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 27 Nov 2007 14:01:23 +0530	
 * Pattern Version:1.0
 */

class BPMPoliciesVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $Id;
public $PolicyName;
public $PolicyDescription;
public $Type;
public $DefaultPolicy;
public $SourceIP;
public $Status;
public $Priority;
public $Share;
public $CumulativeBandwidth;
public $ScheduleType;
public $ScheduleFromTime;
public $ScheduleTOTime;
public $Schedule;
public $lastRunDate;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function BPMPoliciesVO(){

}

/*
	function BPMPoliciesVO(IdIn){
 this->Id=$IdIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
	$this->CumulativeBandwidth="0";
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_id() {
	return $this->Id;
}
function set_id($IdIn) { 
	$this->Id=$IdIn;
}

function isset_id() {
	return isset($this->Id);
}


function get_policy_name() {
	return $this->PolicyName;
}
function set_policy_name($PolicyNameIn) { 
	$this->PolicyName=$PolicyNameIn;
}

function isset_policy_name() {
	return isset($this->PolicyName);
}


function get_policy_descr_iption() {
	return $this->PolicyDescription;
}
function set_policy_descr_iption($PolicyDescriptionIn) { 
	$this->PolicyDescription=$PolicyDescriptionIn;
}

function isset_policy_descr_iption() {
	return isset($this->PolicyDescription);
}


function get_type() {
	return $this->Type;
}
function set_type($TypeIn) { 
	$this->Type=$TypeIn;
}

function isset_type() {
	return isset($this->Type);
}


function get_default_policy() {
	return $this->DefaultPolicy;
}
function set_default_policy($DefaultPolicyIn) { 
	$this->DefaultPolicy=$DefaultPolicyIn;
}

function isset_default_policy() {
	return isset($this->DefaultPolicy);
}


function get_source_ip() {
	return $this->SourceIP;
}
function set_source_ip($SourceIPIn) { 
	$this->SourceIP=$SourceIPIn;
}

function isset_source_ip() {
	return isset($this->SourceIP);
}


function get_status() {
	return $this->Status;
}
function set_status($StatusIn) { 
	$this->Status=$StatusIn;
}

function isset_status() {
	return isset($this->Status);
}


function get_priority() {
	return $this->Priority;
}
function set_priority($PriorityIn) { 
	$this->Priority=$PriorityIn;
}

function isset_priority() {
	return isset($this->Priority);
}


function get_share() {
	return $this->Share;
}
function set_share($ShareIn) { 
	$this->Share=$ShareIn;
}

function isset_share() {
	return isset($this->Share);
}


function get_cumulative_bandwidth() {
	return $this->CumulativeBandwidth;
}
function set_cumulative_bandwidth($CumulativeBandwidthIn) { 
	$this->CumulativeBandwidth=$CumulativeBandwidthIn;
}

function isset_cumulative_bandwidth() {
	return isset($this->CumulativeBandwidth);
}


function get_schedule_type() {
	return $this->ScheduleType;
}
function set_schedule_type($ScheduleTypeIn) { 
	$this->ScheduleType=$ScheduleTypeIn;
}

function isset_schedule_type() {
	return isset($this->ScheduleType);
}


function get_schedule_from_time() {
	return $this->ScheduleFromTime;
}
function set_schedule_from_time($ScheduleFromTimeIn) { 
	$this->ScheduleFromTime=$ScheduleFromTimeIn;
}

function isset_schedule_from_time() {
	return isset($this->ScheduleFromTime);
}


function get_schedule_to_time() {
	return $this->ScheduleTOTime;
}
function set_schedule_to_time($ScheduleTOTimeIn) { 
	$this->ScheduleTOTime=$ScheduleTOTimeIn;
}

function isset_schedule_to_time() {
	return isset($this->ScheduleTOTime);
}


function get_schedule() {
	return $this->Schedule;
}
function set_schedule($ScheduleIn) { 
	$this->Schedule=$ScheduleIn;
}

function isset_schedule() {
	return isset($this->Schedule);
}


function get_last_run_date() {
	return $this->lastRunDate;
}
function set_last_run_date($lastRunDateIn) { 
	$this->lastRunDate=$lastRunDateIn;
}

function isset_last_run_date() {
	return isset($this->lastRunDate);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($IdIn,$PolicyNameIn,$PolicyDescriptionIn,$TypeIn,$DefaultPolicyIn,$SourceIPIn,$StatusIn,$PriorityIn,$ShareIn,$CumulativeBandwidthIn,$ScheduleTypeIn,$ScheduleFromTimeIn,$ScheduleTOTimeIn,$ScheduleIn,$lastRunDateIn){
	$this->Id=$IdIn;
	$this->PolicyName=$PolicyNameIn;
	$this->PolicyDescription=$PolicyDescriptionIn;
	$this->Type=$TypeIn;
	$this->DefaultPolicy=$DefaultPolicyIn;
	$this->SourceIP=$SourceIPIn;
	$this->Status=$StatusIn;
	$this->Priority=$PriorityIn;
	$this->Share=$ShareIn;
	$this->CumulativeBandwidth=$CumulativeBandwidthIn;
	$this->ScheduleType=$ScheduleTypeIn;
	$this->ScheduleFromTime=$ScheduleFromTimeIn;
	$this->ScheduleTOTime=$ScheduleTOTimeIn;
	$this->Schedule=$ScheduleIn;
	$this->lastRunDate=$lastRunDateIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->Id=$ary["Id"];
	$this->PolicyName=$ary["PolicyName"];
	$this->PolicyDescription=$ary["PolicyDescription"];
	$this->Type=$ary["Type"];
	$this->DefaultPolicy=$ary["DefaultPolicy"];
	$this->SourceIP=$ary["SourceIP"];
	$this->Status=$ary["Status"];
	$this->Priority=$ary["Priority"];
	$this->Share=$ary["Share"];
	$this->CumulativeBandwidth=$ary["CumulativeBandwidth"];
	$this->ScheduleType=$ary["ScheduleType"];
	$this->ScheduleFromTime=$ary["ScheduleFromTime"];
	$this->ScheduleTOTime=$ary["ScheduleTOTime"];
	$this->Schedule=$ary["Schedule"];
	$this->lastRunDate=$ary["lastRunDate"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["Id"]=$this->Id;
		$oAry["PolicyName"]=$this->PolicyName;
		$oAry["PolicyDescription"]=$this->PolicyDescription;
		$oAry["Type"]=$this->Type;
		$oAry["DefaultPolicy"]=$this->DefaultPolicy;
		$oAry["SourceIP"]=$this->SourceIP;
		$oAry["Status"]=$this->Status;
		$oAry["Priority"]=$this->Priority;
		$oAry["Share"]=$this->Share;
		$oAry["CumulativeBandwidth"]=$this->CumulativeBandwidth;
		$oAry["ScheduleType"]=$this->ScheduleType;
		$oAry["ScheduleFromTime"]=$this->ScheduleFromTime;
		$oAry["ScheduleTOTime"]=$this->ScheduleTOTime;
		$oAry["Schedule"]=$this->Schedule;
		$oAry["lastRunDate"]=$this->lastRunDate;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_id() != $this->Id) {
		return(false);
	}
	if ($valueObject->get_policy_name() != $this->PolicyName) {
		return(false);
	}
	if ($valueObject->get_policy_descr_iption() != $this->PolicyDescription) {
		return(false);
	}
	if ($valueObject->get_type() != $this->Type) {
		return(false);
	}
	if ($valueObject->get_default_policy() != $this->DefaultPolicy) {
		return(false);
	}
	if ($valueObject->get_source_ip() != $this->SourceIP) {
		return(false);
	}
	if ($valueObject->get_status() != $this->Status) {
		return(false);
	}
	if ($valueObject->get_priority() != $this->Priority) {
		return(false);
	}
	if ($valueObject->get_share() != $this->Share) {
		return(false);
	}
	if ($valueObject->get_cumulative_bandwidth() != $this->CumulativeBandwidth) {
		return(false);
	}
	if ($valueObject->get_schedule_type() != $this->ScheduleType) {
		return(false);
	}
	if ($valueObject->get_schedule_from_time() != $this->ScheduleFromTime) {
		return(false);
	}
	if ($valueObject->get_schedule_to_time() != $this->ScheduleTOTime) {
		return(false);
	}
	if ($valueObject->get_schedule() != $this->Schedule) {
		return(false);
	}
	if ($valueObject->get_last_run_date() != $this->lastRunDate) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass BPMPoliciesVO, mapping to table BPMPolicies\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."Id = ".$this->Id."\n";
	$out = $out."PolicyName = ".$this->PolicyName."\n";
	$out = $out."PolicyDescription = ".$this->PolicyDescription."\n";
	$out = $out."Type = ".$this->Type."\n";
	$out = $out."DefaultPolicy = ".$this->DefaultPolicy."\n";
	$out = $out."SourceIP = ".$this->SourceIP."\n";
	$out = $out."Status = ".$this->Status."\n";
	$out = $out."Priority = ".$this->Priority."\n";
	$out = $out."Share = ".$this->Share."\n";
	$out = $out."CumulativeBandwidth = ".$this->CumulativeBandwidth."\n";
	$out = $out."ScheduleType = ".$this->ScheduleType."\n";
	$out = $out."ScheduleFromTime = ".$this->ScheduleFromTime."\n";
	$out = $out."ScheduleTOTime = ".$this->ScheduleTOTime."\n";
	$out = $out."Schedule = ".$this->Schedule."\n";
	$out = $out."lastRunDate = ".$this->lastRunDate."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new BPMPoliciesVO();
	
	 $cloned->set_id($this->Id);
	 $cloned->set_policy_name($this->PolicyName);
	 $cloned->set_policy_descr_iption($this->PolicyDescription);
	 $cloned->set_type($this->Type);
	 $cloned->set_default_policy($this->DefaultPolicy);
	 $cloned->set_source_ip($this->SourceIP);
	 $cloned->set_status($this->Status);
	 $cloned->set_priority($this->Priority);
	 $cloned->set_share($this->Share);
	 $cloned->set_cumulative_bandwidth($this->CumulativeBandwidth);
	 $cloned->set_schedule_type($this->ScheduleType);
	 $cloned->set_schedule_from_time($this->ScheduleFromTime);
	 $cloned->set_schedule_to_time($this->ScheduleTOTime);
	 $cloned->set_schedule($this->Schedule);
	 $cloned->set_last_run_date($this->lastRunDate);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
