<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * cxClusterLog Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 27 Nov 2007 14:01:23 +0530	
 * Pattern Version:1.0
 */

class CxClusterLogVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $id;
public $errorString;
public $timeString;
public $alertSent;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function CxClusterLogVO(){

}

/*
	function CxClusterLogVO(idIn){
 this->id=$idIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
	$this->alertSent="0";
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_id() {
	return $this->id;
}
function set_id($idIn) { 
	$this->id=$idIn;
}

function isset_id() {
	return isset($this->id);
}


function get_error_string() {
	return $this->errorString;
}
function set_error_string($errorStringIn) { 
	$this->errorString=$errorStringIn;
}

function isset_error_string() {
	return isset($this->errorString);
}


function get_time_string() {
	return $this->timeString;
}
function set_time_string($timeStringIn) { 
	$this->timeString=$timeStringIn;
}

function isset_time_string() {
	return isset($this->timeString);
}


function get_alert_sent() {
	return $this->alertSent;
}
function set_alert_sent($alertSentIn) { 
	$this->alertSent=$alertSentIn;
}

function isset_alert_sent() {
	return isset($this->alertSent);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($idIn,$errorStringIn,$timeStringIn,$alertSentIn){
	$this->id=$idIn;
	$this->errorString=$errorStringIn;
	$this->timeString=$timeStringIn;
	$this->alertSent=$alertSentIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->id=$ary["id"];
	$this->errorString=$ary["errorString"];
	$this->timeString=$ary["timeString"];
	$this->alertSent=$ary["alertSent"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["id"]=$this->id;
		$oAry["errorString"]=$this->errorString;
		$oAry["timeString"]=$this->timeString;
		$oAry["alertSent"]=$this->alertSent;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_id() != $this->id) {
		return(false);
	}
	if ($valueObject->get_error_string() != $this->errorString) {
		return(false);
	}
	if ($valueObject->get_time_string() != $this->timeString) {
		return(false);
	}
	if ($valueObject->get_alert_sent() != $this->alertSent) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass CxClusterLogVO, mapping to table cxClusterLog\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."id = ".$this->id."\n";
	$out = $out."errorString = ".$this->errorString."\n";
	$out = $out."timeString = ".$this->timeString."\n";
	$out = $out."alertSent = ".$this->alertSent."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new CxClusterLogVO();
	
	 $cloned->set_id($this->id);
	 $cloned->set_error_string($this->errorString);
	 $cloned->set_time_string($this->timeString);
	 $cloned->set_alert_sent($this->alertSent);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
