<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * exportedISCSILuns Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 17 Jun 2008 14:28:35 +0530	
 * Pattern Version:1.0
 */

class ExportedISCSILunsVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $exportedDeviceName;
public $hostId;
public $exportedISCSILunId;
public $lunNumber;
public $lunCapacity;
public $initiatorIPAddress;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function ExportedISCSILunsVO(){

}

/*
	function ExportedISCSILunsVO(exportedDeviceNameIn,exportedISCSILunIdIn,hostIdIn){
 this->exportedDeviceName=$exportedDeviceNameIn;
 this->exportedISCSILunId=$exportedISCSILunIdIn;
 this->hostId=$hostIdIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_exported_device_name() {
	return $this->exportedDeviceName;
}
function set_exported_device_name($exportedDeviceNameIn) { 
	$this->exportedDeviceName=$exportedDeviceNameIn;
}

function isset_exported_device_name() {
	return isset($this->exportedDeviceName);
}


function get_host_id() {
	return $this->hostId;
}
function set_host_id($hostIdIn) { 
	$this->hostId=$hostIdIn;
}

function isset_host_id() {
	return isset($this->hostId);
}


function get_exported_i_s_c_s_i_lun_id() {
	return $this->exportedISCSILunId;
}
function set_exported_i_s_c_s_i_lun_id($exportedISCSILunIdIn) { 
	$this->exportedISCSILunId=$exportedISCSILunIdIn;
}

function isset_exported_i_s_c_s_i_lun_id() {
	return isset($this->exportedISCSILunId);
}


function get_lun_number() {
	return $this->lunNumber;
}
function set_lun_number($lunNumberIn) { 
	$this->lunNumber=$lunNumberIn;
}

function isset_lun_number() {
	return isset($this->lunNumber);
}


function get_lun_capacity() {
	return $this->lunCapacity;
}
function set_lun_capacity($lunCapacityIn) { 
	$this->lunCapacity=$lunCapacityIn;
}

function isset_lun_capacity() {
	return isset($this->lunCapacity);
}


function get_initiator_ip_address() {
	return $this->initiatorIPAddress;
}
function set_initiator_ip_address($initiatorIPAddressIn) { 
	$this->initiatorIPAddress=$initiatorIPAddressIn;
}

function isset_initiator_ip_address() {
	return isset($this->initiatorIPAddress);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($exportedDeviceNameIn,$hostIdIn,$exportedISCSILunIdIn,$lunNumberIn,$lunCapacityIn,$initiatorIPAddressIn){
	$this->exportedDeviceName=$exportedDeviceNameIn;
	$this->hostId=$hostIdIn;
	$this->exportedISCSILunId=$exportedISCSILunIdIn;
	$this->lunNumber=$lunNumberIn;
	$this->lunCapacity=$lunCapacityIn;
	$this->initiatorIPAddress=$initiatorIPAddressIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->exportedDeviceName=$ary["exportedDeviceName"];
	$this->hostId=$ary["hostId"];
	$this->exportedISCSILunId=$ary["exportedISCSILunId"];
	$this->lunNumber=$ary["lunNumber"];
	$this->lunCapacity=$ary["lunCapacity"];
	$this->initiatorIPAddress=$ary["initiatorIPAddress"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["exportedDeviceName"]=$this->exportedDeviceName;
		$oAry["hostId"]=$this->hostId;
		$oAry["exportedISCSILunId"]=$this->exportedISCSILunId;
		$oAry["lunNumber"]=$this->lunNumber;
		$oAry["lunCapacity"]=$this->lunCapacity;
		$oAry["initiatorIPAddress"]=$this->initiatorIPAddress;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_exported_device_name() != $this->exportedDeviceName) {
		return(false);
	}
	if ($valueObject->get_host_id() != $this->hostId) {
		return(false);
	}
	if ($valueObject->get_exported_i_s_c_s_i_lun_id() != $this->exportedISCSILunId) {
		return(false);
	}
	if ($valueObject->get_lun_number() != $this->lunNumber) {
		return(false);
	}
	if ($valueObject->get_lun_capacity() != $this->lunCapacity) {
		return(false);
	}
	if ($valueObject->get_initiator_ip_address() != $this->initiatorIPAddress) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass ExportedISCSILunsVO, mapping to table exportedISCSILuns\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."exportedDeviceName = ".$this->exportedDeviceName."\n";
	$out = $out."hostId = ".$this->hostId."\n";
	$out = $out."exportedISCSILunId = ".$this->exportedISCSILunId."\n";
	$out = $out."lunNumber = ".$this->lunNumber."\n";
	$out = $out."lunCapacity = ".$this->lunCapacity."\n";
	$out = $out."initiatorIPAddress = ".$this->initiatorIPAddress."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new ExportedISCSILunsVO();
	
	 $cloned->set_exported_device_name($this->exportedDeviceName);
	 $cloned->set_host_id($this->hostId);
	 $cloned->set_exported_i_s_c_s_i_lun_id($this->exportedISCSILunId);
	 $cloned->set_lun_number($this->lunNumber);
	 $cloned->set_lun_capacity($this->lunCapacity);
	 $cloned->set_initiator_ip_address($this->initiatorIPAddress);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
