<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * exportedMountPoints Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 17 Jun 2008 14:28:36 +0530	
 * Pattern Version:1.0
 */

class ExportedMountPointsVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $hostId;
public $exportedDeviceName;
public $mountPoint;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function ExportedMountPointsVO(){

}

/*
	function ExportedMountPointsVO(exportedDeviceNameIn,hostIdIn,mountPointIn){
 this->exportedDeviceName=$exportedDeviceNameIn;
 this->hostId=$hostIdIn;
 this->mountPoint=$mountPointIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_host_id() {
	return $this->hostId;
}
function set_host_id($hostIdIn) { 
	$this->hostId=$hostIdIn;
}

function isset_host_id() {
	return isset($this->hostId);
}


function get_exported_device_name() {
	return $this->exportedDeviceName;
}
function set_exported_device_name($exportedDeviceNameIn) { 
	$this->exportedDeviceName=$exportedDeviceNameIn;
}

function isset_exported_device_name() {
	return isset($this->exportedDeviceName);
}


function get_mount_point() {
	return $this->mountPoint;
}
function set_mount_point($mountPointIn) { 
	$this->mountPoint=$mountPointIn;
}

function isset_mount_point() {
	return isset($this->mountPoint);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($hostIdIn,$exportedDeviceNameIn,$mountPointIn){
	$this->hostId=$hostIdIn;
	$this->exportedDeviceName=$exportedDeviceNameIn;
	$this->mountPoint=$mountPointIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->hostId=$ary["hostId"];
	$this->exportedDeviceName=$ary["exportedDeviceName"];
	$this->mountPoint=$ary["mountPoint"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["hostId"]=$this->hostId;
		$oAry["exportedDeviceName"]=$this->exportedDeviceName;
		$oAry["mountPoint"]=$this->mountPoint;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_host_id() != $this->hostId) {
		return(false);
	}
	if ($valueObject->get_exported_device_name() != $this->exportedDeviceName) {
		return(false);
	}
	if ($valueObject->get_mount_point() != $this->mountPoint) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass ExportedMountPointsVO, mapping to table exportedMountPoints\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."hostId = ".$this->hostId."\n";
	$out = $out."exportedDeviceName = ".$this->exportedDeviceName."\n";
	$out = $out."mountPoint = ".$this->mountPoint."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new ExportedMountPointsVO();
	
	 $cloned->set_host_id($this->hostId);
	 $cloned->set_exported_device_name($this->exportedDeviceName);
	 $cloned->set_mount_point($this->mountPoint);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
