<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * frbGlobalSettings Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 27 Nov 2007 14:01:25 +0530	
 * Pattern Version:1.0
 */

class FrbGlobalSettingsVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $autoClearLogYear;
public $autoClearLogMonth;
public $autoClearLogWeek;
public $autoClearLogDay;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function FrbGlobalSettingsVO(){

}

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
	$this->autoClearLogYear="0";
	$this->autoClearLogMonth="0";
	$this->autoClearLogWeek="0";
	$this->autoClearLogDay="0";
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_auto_clear_log_year() {
	return $this->autoClearLogYear;
}
function set_auto_clear_log_year($autoClearLogYearIn) { 
	$this->autoClearLogYear=$autoClearLogYearIn;
}

function isset_auto_clear_log_year() {
	return isset($this->autoClearLogYear);
}


function get_auto_clear_log_month() {
	return $this->autoClearLogMonth;
}
function set_auto_clear_log_month($autoClearLogMonthIn) { 
	$this->autoClearLogMonth=$autoClearLogMonthIn;
}

function isset_auto_clear_log_month() {
	return isset($this->autoClearLogMonth);
}


function get_auto_clear_log_week() {
	return $this->autoClearLogWeek;
}
function set_auto_clear_log_week($autoClearLogWeekIn) { 
	$this->autoClearLogWeek=$autoClearLogWeekIn;
}

function isset_auto_clear_log_week() {
	return isset($this->autoClearLogWeek);
}


function get_auto_clear_log_day() {
	return $this->autoClearLogDay;
}
function set_auto_clear_log_day($autoClearLogDayIn) { 
	$this->autoClearLogDay=$autoClearLogDayIn;
}

function isset_auto_clear_log_day() {
	return isset($this->autoClearLogDay);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($autoClearLogYearIn,$autoClearLogMonthIn,$autoClearLogWeekIn,$autoClearLogDayIn){
	$this->autoClearLogYear=$autoClearLogYearIn;
	$this->autoClearLogMonth=$autoClearLogMonthIn;
	$this->autoClearLogWeek=$autoClearLogWeekIn;
	$this->autoClearLogDay=$autoClearLogDayIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->autoClearLogYear=$ary["autoClearLogYear"];
	$this->autoClearLogMonth=$ary["autoClearLogMonth"];
	$this->autoClearLogWeek=$ary["autoClearLogWeek"];
	$this->autoClearLogDay=$ary["autoClearLogDay"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["autoClearLogYear"]=$this->autoClearLogYear;
		$oAry["autoClearLogMonth"]=$this->autoClearLogMonth;
		$oAry["autoClearLogWeek"]=$this->autoClearLogWeek;
		$oAry["autoClearLogDay"]=$this->autoClearLogDay;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_auto_clear_log_year() != $this->autoClearLogYear) {
		return(false);
	}
	if ($valueObject->get_auto_clear_log_month() != $this->autoClearLogMonth) {
		return(false);
	}
	if ($valueObject->get_auto_clear_log_week() != $this->autoClearLogWeek) {
		return(false);
	}
	if ($valueObject->get_auto_clear_log_day() != $this->autoClearLogDay) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass FrbGlobalSettingsVO, mapping to table frbGlobalSettings\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."autoClearLogYear = ".$this->autoClearLogYear."\n";
	$out = $out."autoClearLogMonth = ".$this->autoClearLogMonth."\n";
	$out = $out."autoClearLogWeek = ".$this->autoClearLogWeek."\n";
	$out = $out."autoClearLogDay = ".$this->autoClearLogDay."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new FrbGlobalSettingsVO();
	
	 $cloned->set_auto_clear_log_year($this->autoClearLogYear);
	 $cloned->set_auto_clear_log_month($this->autoClearLogMonth);
	 $cloned->set_auto_clear_log_week($this->autoClearLogWeek);
	 $cloned->set_auto_clear_log_day($this->autoClearLogDay);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
