<?php
/**
  * This sourcecode has been generated by InMage Source Code Generator version 1.0
  * The usage of generated code is restricted to InMage Systems Inc.
  *
  * sanITLNexus Data Access Object[DAO]
  * This class contains all database handling that is needed to 
  * permanently store and retrieve sanITLNexus object instances. 
  * Generated Date:	Tue, 8 Jul 2008 16:01:47 +0530	
  * Pattern Version:1.0
  */
class SanITLNexusDAO
{

/**
 * createValueObject-method. This method is used when the Dao class needs
 * to create new value object instance. The reason why this method exists
 * is that sometimes the programmer may want to extend also the valueObject
 * and then this method can be overrided to return extended valueObject.
 * NOTE: If you extend the valueObject class, make sure to override the
 * clone() method in it!
 */
function createValueObject() {
	return new SanITLNexusVO();
 }

/**
 * getObject-method. This will create and load valueObject contents from database 
 * using given Primary-Key as identifier. This method is just a convenience method 
 * for the real load-method which accepts the valueObject as a parameter. Returned
 * valueObject will be created using the createValueObject() method.
 */
function getObject($conn,$fabricId,$sanInitiatorPortWwn,$sanLunId,$sanLunNumber,$sanTargetPortWwn) {
	$valueObject = $this->createValueObject();
	$valueObject->set_fabric_id($fabricId);
	$valueObject->set_san_initiator_port_wwn($sanInitiatorPortWwn);
	$valueObject->set_san_lun_id($sanLunId);
	$valueObject->set_san_lun_number($sanLunNumber);
	$valueObject->set_san_target_port_wwn($sanTargetPortWwn);
	$this->findByPrimaryKey($conn,$valueObject);
	return $valueObject;
}

/**
 * findbyPrimaryKey-method. This will load valueObject contents from database using
 * Primary-Key as identifier. Upper layer should use this so that valueObject
 * instance is created and only primary-key should be specified. Then call
 * this method to complete other persistent information. This method will
 * overwrite all other fields except primary-key and possible runtime variables.
 * If load can not find matching row, NotFoundException will be thrown.
 *
 * @param conn         This method requires working database connection.
 * @param valueObject  This parameter contains the class instance to be loaded.
 *                     Primary-key field must be set for this to work properly.
 */
function findByPrimaryKey($conn, $valueObject) {

	if (!$valueObject->get_fabric_id()) {
    	//print "Can not select without Primary-Key!";
		return false;
	}

	if (!$valueObject->get_san_initiator_port_wwn()) {
    	//print "Can not select without Primary-Key!";
		return false;
	}

	if (!$valueObject->get_san_lun_id()) {
    	//print "Can not select without Primary-Key!";
		return false;
	}

	if (!$valueObject->get_san_lun_number()) {
    	//print "Can not select without Primary-Key!";
		return false;
	}

	if (!$valueObject->get_san_target_port_wwn()) {
    	//print "Can not select without Primary-Key!";
		return false;
	}

	$sql = "SELECT * FROM sanITLNexus WHERE (fabricId = '".$valueObject->get_fabric_id()."'  AND sanInitiatorPortWwn = '".$valueObject->get_san_initiator_port_wwn()."'  AND sanLunId = '".$valueObject->get_san_lun_id()."'  AND sanLunNumber = '".$valueObject->get_san_lun_number()."'  AND sanTargetPortWwn = '".$valueObject->get_san_target_port_wwn()."') "; 
	if ($this->singleQuery($conn, $sql, $valueObject)){
    	return true;
    }
    else{
    	return false;
	}
}

/**
 * findbyinit_portwwn_and_tgt_portwwn-method. A user defined or custom findbyMethod  
 * This method find the entry by init_portwwn_and_tgt_portwwn in discoveryNexus and sanITLNexus
 *
 * @param conn         This method requires working database connection.
 * @param params       associate array: sql will be searched and replaced by the matching values
 *					   associated with the token
 */
function find_by_init_portwwn_and_tgt_portwwn($conn, $params = array()) {

	$sql = "select count(*) from discoveryNexus d1, sanITLNexus s1 where d1.sanInitiatorPortWwn = s1.sanInitiatorPortWwn and d1.sanTargetPortWwn = s1.sanTargetPortWwn and (s1.state = 'no_work' OR s1.state = 'new_entry')";
	$sql = str_replace(array_keys($params), array_values($params), $sql);
	$searchResults = $this->listQuery($conn, $sql);
	return $searchResults;
		
}

/**
 * findbyportwwn_in_itlnexus_and_srcdest-method. A user defined or custom findbyMethod  
 * This method find the entry by init_portwwn_and_tgt_portwwn in srcLogicalVolumeDestLogicalVolume and sanITLNexus
 *
 * @param conn         This method requires working database connection.
 * @param params       associate array: sql will be searched and replaced by the matching values
 *					   associated with the token
 */
function find_by_portwwn_in_itlnexus_and_srcdest($conn, $params = array()) {

	$sql = "select count(*) from srcLogicalVolumeDestLogicalVolume srcdest, sanITLNexus itl where itl.sanInitiatorPortWwn = 'init_port' and itl.sanTargetPortWwn = 'tgt_port' and itl.fabricId = 'fabric_id' and (srcdest.Phy_Lunid = itl.sanLunId )";
	$sql = str_replace(array_keys($params), array_values($params), $sql);
	$searchResults = $this->listQuery($conn, $sql);
	return $searchResults;
		
}

/**
 * findbywwn_luninfo-method. A user defined or custom findbyMethod  
 * This method find the lun info through the wwn in sanLuns and sanITLNexus
 *
 * @param conn         This method requires working database connection.
 * @param params       associate array: sql will be searched and replaced by the matching values
 *					   associated with the token
 */
function find_by_wwn_luninfo($conn, $params = array()) {

	 $sql = "select itl.sanLunNumber, itl.sanLunId, slun.capacity, slun.blockSize, slun.vendorName, slun.modelNumber from sanLuns slun, sanITLNexus itl where itl.sanInitiatorPortWwn = 'init_port' and itl.sanTargetPortWwn = 'tgt_port' and fabricId = 'fabric_id' and ( slun.sanLunId = itl.sanLunId )";
	$sql = str_replace(array_keys($params), array_values($params), $sql);
	 $searchResults = $this->listQuery($conn, $sql);
	 return $searchResults;
		
}

/**
 * findbyfabricid-method. A user defined or custom findbyMethod  
 * This method select by fabric_id
 *
 * @param conn         This method requires working database connection.
 * @param params       associate array: sql will be searched and replaced by the matching values
 *					   associated with the token
 */
function find_by_fabricid($conn, $params = array()) {

	$sql = "fabricId='fabric_id'";
	$sql = str_replace(array_keys($params), array_values($params), $sql);
	$sql = "SELECT * FROM sanITLNexus WHERE (" . $sql . ")";
	$searchResults = $this->listQuery($conn, $sql);
	return $searchResults;
		
}



/**
 * findAll-method. This will read all contents from database table and
 * build an Vector containing valueObjects. Please note, that this method
 * will consume huge amounts of resources if table has lot's of rows. 
 * This should only be used when target tables have only small amounts
 * of data.
 *
 * @param conn         This method requires working database connection.
 */
function findAll($conn) {
	
	$sql = "SELECT * FROM sanITLNexus ORDER BY fabricId ASC ,sanInitiatorPortWwn ASC ,sanLunId ASC ,sanLunNumber ASC ,sanTargetPortWwn ASC ";
	$searchResults = $this->listQuery($conn, $sql);
	return $searchResults;
}

/**
 * create-method. This will create new row in database according to supplied
 * valueObject contents. Make sure that values for all NOT NULL columns are
 * correctly specified. Also, if this table does not use automatic surrogate-keys
 * the primary-key must be specified. After INSERT command this method will 
 * read the generated primary-key back to valueObject if automatic surrogate-keys
 * were used. 
 *
 * @param conn         This method requires working database connection.
 * @param valueObject  This parameter contains the class instance to be created.
 *                     If automatic surrogate-keys are not used the Primary-key 
 *                     field must be set for this to work properly.
 */
function create($conn, $valueObject) {
	 $count = 0;
     $sql1 = "INSERT INTO sanITLNexus(";
     $sql3 = ") VALUES ("; 
	 
	 if ($valueObject->isset_san_initiator_port_wwn())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."sanInitiatorPortWwn";
 	    $sql4 = $sql4."'".$valueObject->get_san_initiator_port_wwn()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_san_target_port_wwn())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."sanTargetPortWwn";
 	    $sql4 = $sql4."'".$valueObject->get_san_target_port_wwn()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_san_lun_id())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."sanLunId";
 	    $sql4 = $sql4."'".$valueObject->get_san_lun_id()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_san_lun_number())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."sanLunNumber";
 	    $sql4 = $sql4."'".$valueObject->get_san_lun_number()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_fabric_id())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."fabricId";
 	    $sql4 = $sql4."'".$valueObject->get_fabric_id()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_replication_state())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."replicationState";
 	    $sql4 = $sql4."'".$valueObject->get_replication_state()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_delete_state())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."deleteState";
 	    $sql4 = $sql4."'".$valueObject->get_delete_state()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_resync_required())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."resyncRequired";
 	    $sql4 = $sql4."'".$valueObject->get_resync_required()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_appliance_target_path_state())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."applianceTargetPathState";
 	    $sql4 = $sql4."'".$valueObject->get_appliance_target_path_state()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_appliance_target_path_state_change_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."applianceTargetPathStateChangeCount";
 	    $sql4 = $sql4."'".$valueObject->get_appliance_target_path_state_change_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_appliance_target_path_state_ack_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."applianceTargetPathStateAckCount";
 	    $sql4 = $sql4."'".$valueObject->get_appliance_target_path_state_ack_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_appliance_target_path_io_failure_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."applianceTargetPathIoFailureCount";
 	    $sql4 = $sql4."'".$valueObject->get_appliance_target_path_io_failure_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_appliance_target_path_io_failure_ack_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."applianceTargetPathIoFailureAckCount";
 	    $sql4 = $sql4."'".$valueObject->get_appliance_target_path_io_failure_ack_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_physical_target_path_state())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."physicalTargetPathState";
 	    $sql4 = $sql4."'".$valueObject->get_physical_target_path_state()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_physical_target_path_statechangecount())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."physicalTargetPathStatechangecount";
 	    $sql4 = $sql4."'".$valueObject->get_physical_target_path_statechangecount()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_physical_target_path_state_ackcount())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."physicalTargetPathStateAckcount";
 	    $sql4 = $sql4."'".$valueObject->get_physical_target_path_state_ackcount()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_physical_target_path_io_failure_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."physicalTargetPathIoFailureCount";
 	    $sql4 = $sql4."'".$valueObject->get_physical_target_path_io_failure_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_physical_target_path_io_failure_ack_count())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."physicalTargetPathIoFailureAckCount";
 	    $sql4 = $sql4."'".$valueObject->get_physical_target_path_io_failure_ack_count()."'"; 	
 		$count++;
 	 }
	 
	 if ($valueObject->isset_state())
 	 {
 	  	if($count>0)
		{
			$sql2 = $sql2 . ",";
			$sql4 = $sql4 . ",";
		}
 	    $sql2 = $sql2."state";
 	    $sql4 = $sql4."'".$valueObject->get_state()."'"; 	
 		$count++;
 	 }
	 
	$sql = $sql1 . $sql2. $sql3. $sql4.")";
	$result = $this->databaseUpdate($conn, $sql);
	return true;
}

/**
 * update-method. This method will save the current state of valueObject to database.
 * Save can not be used to create new instances in database, so upper layer must
 * make sure that the primary-key is correctly specified. Primary-key will indicate
 * which instance is going to be updated in database. If save can not find matching 
 * row, NotFoundException will be thrown.
 *
 * @param conn         This method requires working database connection.
 * @param valueObject  This parameter contains the class instance to be saved.
 *                     Primary-key field must be set for this to work properly.
 */
function update($conn, $valueObject) {
	$count = 0;
	$sql = "UPDATE sanITLNexus SET ";
	if ($valueObject->isset_san_initiator_port_wwn())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."sanInitiatorPortWwn = '".$valueObject->get_san_initiator_port_wwn()."'";
		$count++;
	}
	
	if ($valueObject->isset_san_target_port_wwn())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."sanTargetPortWwn = '".$valueObject->get_san_target_port_wwn()."'";
		$count++;
	}
	
	if ($valueObject->isset_san_lun_id())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."sanLunId = '".$valueObject->get_san_lun_id()."'";
		$count++;
	}
	
	if ($valueObject->isset_san_lun_number())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."sanLunNumber = '".$valueObject->get_san_lun_number()."'";
		$count++;
	}
	
	if ($valueObject->isset_fabric_id())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."fabricId = '".$valueObject->get_fabric_id()."'";
		$count++;
	}
	
	if ($valueObject->isset_replication_state())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."replicationState = '".$valueObject->get_replication_state()."'";
		$count++;
	}
	
	if ($valueObject->isset_delete_state())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."deleteState = '".$valueObject->get_delete_state()."'";
		$count++;
	}
	
	if ($valueObject->isset_resync_required())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."resyncRequired = '".$valueObject->get_resync_required()."'";
		$count++;
	}
	
	if ($valueObject->isset_appliance_target_path_state())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."applianceTargetPathState = '".$valueObject->get_appliance_target_path_state()."'";
		$count++;
	}
	
	if ($valueObject->isset_appliance_target_path_state_change_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."applianceTargetPathStateChangeCount = '".$valueObject->get_appliance_target_path_state_change_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_appliance_target_path_state_ack_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."applianceTargetPathStateAckCount = '".$valueObject->get_appliance_target_path_state_ack_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_appliance_target_path_io_failure_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."applianceTargetPathIoFailureCount = '".$valueObject->get_appliance_target_path_io_failure_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_appliance_target_path_io_failure_ack_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."applianceTargetPathIoFailureAckCount = '".$valueObject->get_appliance_target_path_io_failure_ack_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_physical_target_path_state())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."physicalTargetPathState = '".$valueObject->get_physical_target_path_state()."'";
		$count++;
	}
	
	if ($valueObject->isset_physical_target_path_statechangecount())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."physicalTargetPathStatechangecount = '".$valueObject->get_physical_target_path_statechangecount()."'";
		$count++;
	}
	
	if ($valueObject->isset_physical_target_path_state_ackcount())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."physicalTargetPathStateAckcount = '".$valueObject->get_physical_target_path_state_ackcount()."'";
		$count++;
	}
	
	if ($valueObject->isset_physical_target_path_io_failure_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."physicalTargetPathIoFailureCount = '".$valueObject->get_physical_target_path_io_failure_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_physical_target_path_io_failure_ack_count())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."physicalTargetPathIoFailureAckCount = '".$valueObject->get_physical_target_path_io_failure_ack_count()."'";
		$count++;
	}
	
	if ($valueObject->isset_state())
 	{
		if($count>0)
		{
			$sql = $sql . ",";
		}
		$sql = $sql."state = '".$valueObject->get_state()."'";
		$count++;
	}
	
	$sql = $sql." WHERE (fabricId = '".$valueObject->get_fabric_id()."'  AND sanInitiatorPortWwn = '".$valueObject->get_san_initiator_port_wwn()."'  AND sanLunId = '".$valueObject->get_san_lun_id()."'  AND sanLunNumber = '".$valueObject->get_san_lun_number()."'  AND sanTargetPortWwn = '".$valueObject->get_san_target_port_wwn()."')"; 
	$result = $this->databaseUpdate($conn, $sql);
    if ($result != 1) {
        //print "PrimaryKey Error when updating DB!";
    	return false;
	}
 	return true;
}

/**
 * delete-method. This method will remove the information from database as identified by
 * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
 * be restored by calling save. Restoring can only be done using create method but if 
 * database is using automatic surrogate-keys, the resulting object will have different 
 * primary-key than what it was in the deleted object. If delete can not find matching row,
 * NotFoundException will be thrown.
 *
 * @param conn         This method requires working database connection.
 * @param valueObject  This parameter contains the class instance to be deleted.
 *                     Primary-key field must be set for this to work properly.
 */
function delete($conn, $valueObject) {
	
	if (!$valueObject->get_fabric_id()) {
         //print "Can not delete without Primary-Key!";
         return false;
    }
	
	if (!$valueObject->get_san_initiator_port_wwn()) {
         //print "Can not delete without Primary-Key!";
         return false;
    }
	
	if (!$valueObject->get_san_lun_id()) {
         //print "Can not delete without Primary-Key!";
         return false;
    }
	
	if (!$valueObject->get_san_lun_number()) {
         //print "Can not delete without Primary-Key!";
         return false;
    }
	
	if (!$valueObject->get_san_target_port_wwn()) {
         //print "Can not delete without Primary-Key!";
         return false;
    }
	$sql = "DELETE FROM sanITLNexus WHERE (fabricId = '".$valueObject->get_fabric_id()."'  AND sanInitiatorPortWwn = '".$valueObject->get_san_initiator_port_wwn()."'  AND sanLunId = '".$valueObject->get_san_lun_id()."'  AND sanLunNumber = '".$valueObject->get_san_lun_number()."'  AND sanTargetPortWwn = '".$valueObject->get_san_target_port_wwn()."')"; 
	$result = $this->databaseUpdate($conn, $sql);
    if ($result != 1) {
         //print "PrimaryKey Error when updating DB!";
          return false;
    }
 	return true;
}

/**
 * deleteAll-method. This method will remove all information from the table that matches
 * this DAO and ValueObject couple. This should be the most efficient way to clear table.
 * Once deleteAll has been called, no valueObject that has been created before can be 
 * restored by calling save. Restoring can only be done using create method but if database 
 * is using automatic surrogate-keys, the resulting object will have different primary-key 
 * than what it was in the deleted object. (Note, the implementation of this method should
 * be different with different DB backends.)
 *
 * @param conn         This method requires working database connection.
 */
function deleteAll($conn) {
	$sql = "DELETE FROM sanITLNexus";
	$result = $this->databaseUpdate($conn, $sql);
	return true;
}

/**
 * coutAll-method. This method will return the number of all rows from table that matches
 * this Dao. The implementation will simply execute "select count(primarykey) from table".
 * If table is empty, the return value is 0. This method should be used before calling
 * findAll, to make sure table has not too many rows.
 *
 * @param conn         This method requires working database connection.
 */
function countAll($conn) {
	$sql = "SELECT count(*) FROM sanITLNexus";
	$allRows = 0;
	$result = $conn->execute($sql);
    if ($row = $conn->nextRow($result))
    	$allRows = $row[0];
    return $allRows;
}

/** 
 * searchMatching-Method. This method provides searching capability to 
 * get matching valueObjects from database. It works by searching all 
 * objects that match permanent instance variables of given object.
 * Upper layer should use this by setting some parameters in valueObject
 * and then  call searchMatching. The result will be 0-N objects in vector, 
 * all matching those criteria you specified. Those instance-variables that
 * have NULL values are excluded in search-criteria.
 *
 * @param conn         This method requires working database connection.
 * @param valueObject  This parameter contains the class instance where search will be based.
 *                     Primary-key field should not be set.
 */
function searchMatching($conn, $valueObject) {
	$first = true;
    $sql = "SELECT * FROM sanITLNexus WHERE 1=1 ";
	
	if ($valueObject->get_san_initiator_port_wwn() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND sanInitiatorPortWwn LIKE '".$valueObject->get_san_initiator_port_wwn()."%' ";
    }
	
	if ($valueObject->get_san_target_port_wwn() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND sanTargetPortWwn LIKE '".$valueObject->get_san_target_port_wwn()."%' ";
    }
	
	if ($valueObject->get_san_lun_id() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND sanLunId LIKE '".$valueObject->get_san_lun_id()."%' ";
    }
	
	if ($valueObject->get_san_lun_number() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND sanLunNumber LIKE '".$valueObject->get_san_lun_number()."%' ";
    }
	
	if ($valueObject->get_fabric_id() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND fabricId LIKE '".$valueObject->get_fabric_id()."%' ";
    }
	
	if ($valueObject->get_replication_state() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND replicationState LIKE '".$valueObject->get_replication_state()."%' ";
    }
	
	if ($valueObject->get_delete_state() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND deleteState LIKE '".$valueObject->get_delete_state()."%' ";
    }
	
	if ($valueObject->get_resync_required() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND resyncRequired LIKE '".$valueObject->get_resync_required()."%' ";
    }
	
	if ($valueObject->get_appliance_target_path_state() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND applianceTargetPathState LIKE '".$valueObject->get_appliance_target_path_state()."%' ";
    }
	
	if ($valueObject->get_appliance_target_path_state_change_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND applianceTargetPathStateChangeCount LIKE '".$valueObject->get_appliance_target_path_state_change_count()."%' ";
    }
	
	if ($valueObject->get_appliance_target_path_state_ack_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND applianceTargetPathStateAckCount LIKE '".$valueObject->get_appliance_target_path_state_ack_count()."%' ";
    }
	
	if ($valueObject->get_appliance_target_path_io_failure_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND applianceTargetPathIoFailureCount LIKE '".$valueObject->get_appliance_target_path_io_failure_count()."%' ";
    }
	
	if ($valueObject->get_appliance_target_path_io_failure_ack_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND applianceTargetPathIoFailureAckCount LIKE '".$valueObject->get_appliance_target_path_io_failure_ack_count()."%' ";
    }
	
	if ($valueObject->get_physical_target_path_state() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND physicalTargetPathState LIKE '".$valueObject->get_physical_target_path_state()."%' ";
    }
	
	if ($valueObject->get_physical_target_path_statechangecount() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND physicalTargetPathStatechangecount LIKE '".$valueObject->get_physical_target_path_statechangecount()."%' ";
    }
	
	if ($valueObject->get_physical_target_path_state_ackcount() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND physicalTargetPathStateAckcount LIKE '".$valueObject->get_physical_target_path_state_ackcount()."%' ";
    }
	
	if ($valueObject->get_physical_target_path_io_failure_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND physicalTargetPathIoFailureCount LIKE '".$valueObject->get_physical_target_path_io_failure_count()."%' ";
    }
	
	if ($valueObject->get_physical_target_path_io_failure_ack_count() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND physicalTargetPathIoFailureAckCount LIKE '".$valueObject->get_physical_target_path_io_failure_ack_count()."%' ";
    }
	
	if ($valueObject->get_state() != "") {
    	if ($first) { $first = false; }
        $sql = $sql."AND state LIKE '".$valueObject->get_state()."%' ";
    }
	
	$sql = $sql." ORDER BY ";
	$sql = $sql."fabricId ASC ";
    $sql = $sql .", ";
	$sql = $sql."sanInitiatorPortWwn ASC ";
    $sql = $sql .", ";
	$sql = $sql."sanLunId ASC ";
    $sql = $sql .", ";
	$sql = $sql."sanLunNumber ASC ";
    $sql = $sql .", ";
	$sql = $sql."sanTargetPortWwn ASC ";
    // Prevent accidential full table results.
    // Use findAll if all rows must be returned.
    if ($first)
    	return array();

    $searchResults = $this->listQuery($conn, $sql);
    return $searchResults;
}

/**
 * databaseQuery-method. This method is a helper method for internal use. It will execute
 * all database queries that will return only one row. The resultset will be converted
 * to valueObject. If no rows were found, NotFoundException will be thrown.
 *
 * @param conn         This method requires working database connection.
 * @param stmt         This parameter contains the SQL statement to be excuted.
 * @param valueObject  Class-instance where resulting data will be stored.
 */
 function singleQuery($conn, $sql, $valueObject) {
 	$result = $conn->execute($sql);
	if ($row = $conn->nextRow($result)) {
		$valueObject->setAry($row);
     } else {
        //print " Object Not Found!";
     	return false;
     }
     return true;
 }

/**
 * databaseQuery-method. This method is a helper method for internal use. It will execute
 * all database queries that will return multiple rows. The resultset will be converted
 * to the List of valueObjects. If no rows were found, an empty List will be returned.
 *
 * @param conn         This method requires working database connection.
 * @param stmt         This parameter contains the SQL statement to be excuted.
*/
function listQuery($conn, $sql) {
	$searchResults = array();
    $result = $conn->execute($sql);
    while ($row = $conn->nextRow($result)) {
    	$temp = $this->createValueObject();
    	$temp->setAry($row);
        array_push($searchResults, $temp);
	}
	return $searchResults;
}
/**
 * databaseQuery-method. This method is a helper method for internal use. It will execute
 * all database queries that will return multiple rows. However the results will be unstructured
 * i.e. Not formatted as VO Objects 
 * @param conn         This method requires working database connection.
 * @param stmt         This parameter contains the SQL statement to be excuted.
*/
function listQueryResultset($conn,$sql)
{
	$searchResults = array();
    $result = $conn->execute($sql);
	while ($row = $conn->nextRow($result)) {
        array_push($searchResults, $row);
	}
	return $searchResults;
}

/**
 * databaseUpdate-method. This method is a helper method for internal use. It will execute
 * all database handling that will change the information in tables. SELECT queries will
 * not be executed here however. The return value indicates how many rows were affected.
 * This method will also make sure that if cache is used, it will reset when data changes.
 *
 * @param conn         This method requires working database connection.
 * @param stmt         This parameter contains the SQL statement to be excuted.
 */
function databaseUpdate($conn, $sql) {
	$result = $conn->execute($sql);
	return $result;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPDAO-1.10";
 }

}
?>
