<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * san_it_nexus_filter_rules Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Thu, 21 Feb 2008 18:49:34 +0530	
 * Pattern Version:1.0
 */

class SanItNexusFilterRulesVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $member_type;
public $member_value;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function SanItNexusFilterRulesVO(){

}

/*
	function SanItNexusFilterRulesVO(member_typeIn,member_valueIn){
 this->member_type=$member_typeIn;
 this->member_value=$member_valueIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_member_type() {
	return $this->member_type;
}
function set_member_type($member_typeIn) { 
	$this->member_type=$member_typeIn;
}

function isset_member_type() {
	return isset($this->member_type);
}


function get_member_value() {
	return $this->member_value;
}
function set_member_value($member_valueIn) { 
	$this->member_value=$member_valueIn;
}

function isset_member_value() {
	return isset($this->member_value);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($member_typeIn,$member_valueIn){
	$this->member_type=$member_typeIn;
	$this->member_value=$member_valueIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->member_type=$ary["member_type"];
	$this->member_value=$ary["member_value"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["member_type"]=$this->member_type;
		$oAry["member_value"]=$this->member_value;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_member_type() != $this->member_type) {
		return(false);
	}
	if ($valueObject->get_member_value() != $this->member_value) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass SanItNexusFilterRulesVO, mapping to table san_it_nexus_filter_rules\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."member_type = ".$this->member_type."\n";
	$out = $out."member_value = ".$this->member_value."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new SanItNexusFilterRulesVO();
	
	 $cloned->set_member_type($this->member_type);
	 $cloned->set_member_value($this->member_value);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
