<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * sanReportedITNexus Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Wed, 23 Apr 2008 20:00:09 +0530	
 * Pattern Version:1.0
 */

class SanReportedITNexusVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $sanInitiatorPortWwn;
public $sanTargetPortWwn;
public $fabricId;
public $state;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function SanReportedITNexusVO(){

}

/*
	function SanReportedITNexusVO(fabricIdIn,sanInitiatorPortWwnIn,sanTargetPortWwnIn){
 this->fabricId=$fabricIdIn;
 this->sanInitiatorPortWwn=$sanInitiatorPortWwnIn;
 this->sanTargetPortWwn=$sanTargetPortWwnIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_san_initiator_port_wwn() {
	return $this->sanInitiatorPortWwn;
}
function set_san_initiator_port_wwn($sanInitiatorPortWwnIn) { 
	$this->sanInitiatorPortWwn=$sanInitiatorPortWwnIn;
}

function isset_san_initiator_port_wwn() {
	return isset($this->sanInitiatorPortWwn);
}


function get_san_target_port_wwn() {
	return $this->sanTargetPortWwn;
}
function set_san_target_port_wwn($sanTargetPortWwnIn) { 
	$this->sanTargetPortWwn=$sanTargetPortWwnIn;
}

function isset_san_target_port_wwn() {
	return isset($this->sanTargetPortWwn);
}


function get_fabric_id() {
	return $this->fabricId;
}
function set_fabric_id($fabricIdIn) { 
	$this->fabricId=$fabricIdIn;
}

function isset_fabric_id() {
	return isset($this->fabricId);
}


function get_state() {
	return $this->state;
}
function set_state($stateIn) { 
	$this->state=$stateIn;
}

function isset_state() {
	return isset($this->state);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($sanInitiatorPortWwnIn,$sanTargetPortWwnIn,$fabricIdIn,$stateIn){
	$this->sanInitiatorPortWwn=$sanInitiatorPortWwnIn;
	$this->sanTargetPortWwn=$sanTargetPortWwnIn;
	$this->fabricId=$fabricIdIn;
	$this->state=$stateIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->sanInitiatorPortWwn=$ary["sanInitiatorPortWwn"];
	$this->sanTargetPortWwn=$ary["sanTargetPortWwn"];
	$this->fabricId=$ary["fabricId"];
	$this->state=$ary["state"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["sanInitiatorPortWwn"]=$this->sanInitiatorPortWwn;
		$oAry["sanTargetPortWwn"]=$this->sanTargetPortWwn;
		$oAry["fabricId"]=$this->fabricId;
		$oAry["state"]=$this->state;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_san_initiator_port_wwn() != $this->sanInitiatorPortWwn) {
		return(false);
	}
	if ($valueObject->get_san_target_port_wwn() != $this->sanTargetPortWwn) {
		return(false);
	}
	if ($valueObject->get_fabric_id() != $this->fabricId) {
		return(false);
	}
	if ($valueObject->get_state() != $this->state) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass SanReportedITNexusVO, mapping to table sanReportedITNexus\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."sanInitiatorPortWwn = ".$this->sanInitiatorPortWwn."\n";
	$out = $out."sanTargetPortWwn = ".$this->sanTargetPortWwn."\n";
	$out = $out."fabricId = ".$this->fabricId."\n";
	$out = $out."state = ".$this->state."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new SanReportedITNexusVO();
	
	 $cloned->set_san_initiator_port_wwn($this->sanInitiatorPortWwn);
	 $cloned->set_san_target_port_wwn($this->sanTargetPortWwn);
	 $cloned->set_fabric_id($this->fabricId);
	 $cloned->set_state($this->state);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
