<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * sanSwitches Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Mon, 8 Jun 2009 12:13:53 +0530	
 * Pattern Version:1.0
 */

class SanSwitchesVO
{

/**
 * Global variables 
 */
 
 var $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

var $switchIp;
var $fabricId;
var $username;
var $password;
var $lastUpdatedTime;
var $switchLookUpPreference;
var $errorMessage;
var $state;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function SanSwitchesVO(){

}

/*
	function SanSwitchesVO(fabricIdIn,switchIpIn){
 this->fabricId=$fabricIdIn;
 this->switchIp=$switchIpIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_switch_ip() {
	return $this->switchIp;
}
function set_switch_ip($switchIpIn) { 
	$this->switchIp=$switchIpIn;
}

function isset_switch_ip() {
	return isset($this->switchIp);
}


function get_fabric_id() {
	return $this->fabricId;
}
function set_fabric_id($fabricIdIn) { 
	$this->fabricId=$fabricIdIn;
}

function isset_fabric_id() {
	return isset($this->fabricId);
}


function get_username() {
	return $this->username;
}
function set_username($usernameIn) { 
	$this->username=$usernameIn;
}

function isset_username() {
	return isset($this->username);
}


function get_password() {
	return $this->password;
}
function set_password($passwordIn) { 
	$this->password=$passwordIn;
}

function isset_password() {
	return isset($this->password);
}


function get_last_updated_time() {
	return $this->lastUpdatedTime;
}
function set_last_updated_time($lastUpdatedTimeIn) { 
	$this->lastUpdatedTime=$lastUpdatedTimeIn;
}

function isset_last_updated_time() {
	return isset($this->lastUpdatedTime);
}


function get_switch_look_up_preference() {
	return $this->switchLookUpPreference;
}
function set_switch_look_up_preference($switchLookUpPreferenceIn) { 
	$this->switchLookUpPreference=$switchLookUpPreferenceIn;
}

function isset_switch_look_up_preference() {
	return isset($this->switchLookUpPreference);
}


function get_error_message() {
	return $this->errorMessage;
}
function set_error_message($errorMessageIn) { 
	$this->errorMessage=$errorMessageIn;
}

function isset_error_message() {
	return isset($this->errorMessage);
}


function get_state() {
	return $this->state;
}
function set_state($stateIn) { 
	$this->state=$stateIn;
}

function isset_state() {
	return isset($this->state);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($switchIpIn,$fabricIdIn,$usernameIn,$passwordIn,$lastUpdatedTimeIn,$switchLookUpPreferenceIn,$errorMessageIn,$stateIn){
	$this->switchIp=$switchIpIn;
	$this->fabricId=$fabricIdIn;
	$this->username=$usernameIn;
	$this->password=$passwordIn;
	$this->lastUpdatedTime=$lastUpdatedTimeIn;
	$this->switchLookUpPreference=$switchLookUpPreferenceIn;
	$this->errorMessage=$errorMessageIn;
	$this->state=$stateIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->switchIp=$ary["switchIp"];
	$this->fabricId=$ary["fabricId"];
	$this->username=$ary["username"];
	$this->password=$ary["password"];
	$this->lastUpdatedTime=$ary["lastUpdatedTime"];
	$this->switchLookUpPreference=$ary["switchLookUpPreference"];
	$this->errorMessage=$ary["errorMessage"];
	$this->state=$ary["state"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["switchIp"]=$this->switchIp;
		$oAry["fabricId"]=$this->fabricId;
		$oAry["username"]=$this->username;
		$oAry["password"]=$this->password;
		$oAry["lastUpdatedTime"]=$this->lastUpdatedTime;
		$oAry["switchLookUpPreference"]=$this->switchLookUpPreference;
		$oAry["errorMessage"]=$this->errorMessage;
		$oAry["state"]=$this->state;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_switch_ip() != $this->switchIp) {
		return(false);
	}
	if ($valueObject->get_fabric_id() != $this->fabricId) {
		return(false);
	}
	if ($valueObject->get_username() != $this->username) {
		return(false);
	}
	if ($valueObject->get_password() != $this->password) {
		return(false);
	}
	if ($valueObject->get_last_updated_time() != $this->lastUpdatedTime) {
		return(false);
	}
	if ($valueObject->get_switch_look_up_preference() != $this->switchLookUpPreference) {
		return(false);
	}
	if ($valueObject->get_error_message() != $this->errorMessage) {
		return(false);
	}
	if ($valueObject->get_state() != $this->state) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass SanSwitchesVO, mapping to table sanSwitches\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."switchIp = ".$this->switchIp."\n";
	$out = $out."fabricId = ".$this->fabricId."\n";
	$out = $out."username = ".$this->username."\n";
	$out = $out."password = ".$this->password."\n";
	$out = $out."lastUpdatedTime = ".$this->lastUpdatedTime."\n";
	$out = $out."switchLookUpPreference = ".$this->switchLookUpPreference."\n";
	$out = $out."errorMessage = ".$this->errorMessage."\n";
	$out = $out."state = ".$this->state."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new SanSwitchesVO();
	
	 $cloned->set_switch_ip($this->switchIp);
	 $cloned->set_fabric_id($this->fabricId);
	 $cloned->set_username($this->username);
	 $cloned->set_password($this->password);
	 $cloned->set_last_updated_time($this->lastUpdatedTime);
	 $cloned->set_switch_look_up_preference($this->switchLookUpPreference);
	 $cloned->set_error_message($this->errorMessage);
	 $cloned->set_state($this->state);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
