<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * sanVt_vi_info Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 27 Nov 2007 14:01:29 +0530	
 * Pattern Version:1.0
 */

class SanVtViInfoVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $id;
public $portwwn;
public $nodewwn;
public $type;
public $v_portwwn;
public $v_nodewwn;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function SanVtViInfoVO(){

}

/*
	function SanVtViInfoVO(idIn){
 this->id=$idIn;
}
*/

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_id() {
	return $this->id;
}
function set_id($idIn) { 
	$this->id=$idIn;
}

function isset_id() {
	return isset($this->id);
}


function get_portwwn() {
	return $this->portwwn;
}
function set_portwwn($portwwnIn) { 
	$this->portwwn=$portwwnIn;
}

function isset_portwwn() {
	return isset($this->portwwn);
}


function get_nodewwn() {
	return $this->nodewwn;
}
function set_nodewwn($nodewwnIn) { 
	$this->nodewwn=$nodewwnIn;
}

function isset_nodewwn() {
	return isset($this->nodewwn);
}


function get_type() {
	return $this->type;
}
function set_type($typeIn) { 
	$this->type=$typeIn;
}

function isset_type() {
	return isset($this->type);
}


function get_v_portwwn() {
	return $this->v_portwwn;
}
function set_v_portwwn($v_portwwnIn) { 
	$this->v_portwwn=$v_portwwnIn;
}

function isset_v_portwwn() {
	return isset($this->v_portwwn);
}


function get_v_nodewwn() {
	return $this->v_nodewwn;
}
function set_v_nodewwn($v_nodewwnIn) { 
	$this->v_nodewwn=$v_nodewwnIn;
}

function isset_v_nodewwn() {
	return isset($this->v_nodewwn);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($idIn,$portwwnIn,$nodewwnIn,$typeIn,$v_portwwnIn,$v_nodewwnIn){
	$this->id=$idIn;
	$this->portwwn=$portwwnIn;
	$this->nodewwn=$nodewwnIn;
	$this->type=$typeIn;
	$this->v_portwwn=$v_portwwnIn;
	$this->v_nodewwn=$v_nodewwnIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->id=$ary["id"];
	$this->portwwn=$ary["portwwn"];
	$this->nodewwn=$ary["nodewwn"];
	$this->type=$ary["type"];
	$this->v_portwwn=$ary["v_portwwn"];
	$this->v_nodewwn=$ary["v_nodewwn"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["id"]=$this->id;
		$oAry["portwwn"]=$this->portwwn;
		$oAry["nodewwn"]=$this->nodewwn;
		$oAry["type"]=$this->type;
		$oAry["v_portwwn"]=$this->v_portwwn;
		$oAry["v_nodewwn"]=$this->v_nodewwn;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_id() != $this->id) {
		return(false);
	}
	if ($valueObject->get_portwwn() != $this->portwwn) {
		return(false);
	}
	if ($valueObject->get_nodewwn() != $this->nodewwn) {
		return(false);
	}
	if ($valueObject->get_type() != $this->type) {
		return(false);
	}
	if ($valueObject->get_v_portwwn() != $this->v_portwwn) {
		return(false);
	}
	if ($valueObject->get_v_nodewwn() != $this->v_nodewwn) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass SanVtViInfoVO, mapping to table sanVt_vi_info\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."id = ".$this->id."\n";
	$out = $out."portwwn = ".$this->portwwn."\n";
	$out = $out."nodewwn = ".$this->nodewwn."\n";
	$out = $out."type = ".$this->type."\n";
	$out = $out."v_portwwn = ".$this->v_portwwn."\n";
	$out = $out."v_nodewwn = ".$this->v_nodewwn."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new SanVtViInfoVO();
	
	 $cloned->set_id($this->id);
	 $cloned->set_portwwn($this->portwwn);
	 $cloned->set_nodewwn($this->nodewwn);
	 $cloned->set_type($this->type);
	 $cloned->set_v_portwwn($this->v_portwwn);
	 $cloned->set_v_nodewwn($this->v_nodewwn);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
