<?php
/**
 * This sourcecode has been generated by InMage Source Code Generator version 1.0
 * The usage of generated code is restricted to InMage Systems Inc.
 *
 * userErrorReceivers Value Object[VO]
 * This class is value object representing database table host
 * This class is needs to be used with associated Dao object
 * Generated Date:	Tue, 27 Nov 2007 14:01:30 +0530	
 * Pattern Version:1.0
 */

class UserErrorReceiversVO
{

/**
 * Global variables 
 */
 
 public $ary;
 
 
 
/** 
 * Persistent Instance variables. This data is directly 
 * mapped to the columns of database table.
 */

public $UID;
public $pairId;
public $sendEmail;

/** 
 * Constructors. Code generator generates two constructors by default.
 * The first one takes no arguments and provides the most simple
 * way to create object instance. The another one takes one
 * argument, which is the primary key of the corresponding table.
 */

function UserErrorReceiversVO(){

}

/** 
 * Initializes the variables with database specific 
 * defaults.
 */
 function initialize(){
 
	$this->UID="0";
	$this->pairId="0";
	$this->sendEmail="0";
 }
 
/** 
 * Get and Set methods for persistent variables. 
 */

function get_u_id() {
	return $this->UID;
}
function set_u_id($UIDIn) { 
	$this->UID=$UIDIn;
}

function isset_u_id() {
	return isset($this->UID);
}


function get_pair_id() {
	return $this->pairId;
}
function set_pair_id($pairIdIn) { 
	$this->pairId=$pairIdIn;
}

function isset_pair_id() {
	return isset($this->pairId);
}


function get_send_email() {
	return $this->sendEmail;
}
function set_send_email($sendEmailIn) { 
	$this->sendEmail=$sendEmailIn;
}

function isset_send_email() {
	return isset($this->sendEmail);
}


/** 
 * setAll allows to set all persistent variables in one method call.
 * This is useful, when all data is available and it is needed to 
 * set the initial state of this object. Note that this method will
 * directly modify instance variales, without going trough the 
 * individual set-methods.
 */
function setAll($UIDIn,$pairIdIn,$sendEmailIn){
	$this->UID=$UIDIn;
	$this->pairId=$pairIdIn;
	$this->sendEmail=$sendEmailIn;
}

/** 
 * setAry allows copy the contents of an associative array 
 * to the member variables
 */
function setAry($ary){ 
	$this->ary=$ary;
	$this->UID=$ary["UID"];
	$this->pairId=$ary["pairId"];
	$this->sendEmail=$ary["sendEmail"];
}

/** 
 * returns an associative array representing the object
 * if the object values are loaded as result of DB operation, then the array
 * return would equivalent of the row returned DB resultset 
 */
function getAry(){ 
	$oAry = array();
	if (isset($this->ary))
	{
		$oAry = $this->ary;
	}
	else
	{
		$oAry["UID"]=$this->UID;
		$oAry["pairId"]=$this->pairId;
		$oAry["sendEmail"]=$this->sendEmail;
	}
	return $oAry;
} 

 /** 
  * hasEqualMapping-method will compare two Host instances
  * and return true if they contain same values in all persistent instance 
  * variables. If hasEqualMapping returns true, it does not mean the objects
  * are the same instance. However it does mean that in that moment, they 
  * are mapped to the same row in database.
  */
function hasEqualMapping($valueObject){
	if ($valueObject->get_u_id() != $this->UID) {
		return(false);
	}
	if ($valueObject->get_pair_id() != $this->pairId) {
		return(false);
	}
	if ($valueObject->get_send_email() != $this->sendEmail) {
		return(false);
	}
    return true;
 }
 
/**
 * toString will return String object representing the state of this 
 * valueObject. This is useful during application development, and 
 * possibly when application is writing object states in textlog.
 */
function toString() {
	$out = $this->get_codegen_version();
	$out = $out."\nclass UserErrorReceiversVO, mapping to table userErrorReceivers\n";
	$out = $out."Persistent attributes: \n";
	$out = $out."UID = ".$this->UID."\n";
	$out = $out."pairId = ".$this->pairId."\n";
	$out = $out."sendEmail = ".$this->sendEmail."\n";
	return $out;
}

/**
 * Clone will return identical deep copy of this valueObject.
 * Here, the retuned cloned object will have all its attributes cloned
 */
function __clone() {
	$cloned = new UserErrorReceiversVO();
	
	 $cloned->set_u_id($this->UID);
	 $cloned->set_pair_id($this->pairId);
	 $cloned->set_send_email($this->sendEmail);
	
	return $cloned;
}

/** 
 * getCodegenVersion will return information about
 * generator which created these sources.
 */
function get_codegen_version() {
    return  "1.0";
 }
/** 
 * getCodegenTemplateVersion will return information about
 * generator which created these sources.
 */
function get_codegen_template_version() {
    return  "PHPVO-1.7";
 }

}
?>
