#!/bin/sh
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

_vxdir=""
$_vxdir/bin/check_drivers.sh noinitrd

hostonly='' instmods involflt
