include top.mak

SRCS = \
	 diffdatasort.cpp  \
    ../dataprotection/diffsortcriterion.cpp

TEST_SRCS = 

X_CFLAGS = \
	-Idataprotection \
	-Icdpapplylib \
	-Icommon \
    -Iinmsafeint \
    -Iinmsafeint/$(X_MAJOR_ARCH) \
	-Iinmsafecapis \
	-Iinmsafecapis/$(X_MAJOR_ARCH) \
	$(BOOST_INCLUDE) \

X_LIBS = 

X_THIRDPARTY_LIBS = 

X_SYSTEM_LIBS = 

X_LDFLAGS =

BINARY=diffdatasort
BINARY_EXT=$(X_EXEEXT)

include bottom.mak

