#ifndef PLATFORM_FILECONFIGURATORDEFS_H
#define PLATFORM_FILECONFIGURATORDEFS_H

#define DEFAULT_VM_CMDS_FOR_PATS ""
#define DEFAULT_VM_PATS ""
#define DEFAULT_VM_CMDS ""
#define POWERMTCMD ""
#define VXDMPCMD ""
#define VXDISKCMD ""
#define VXVSETCMD ""
#define GREPCMD  ""
#define AWKCMD  ""

#endif /* PLATFORM_FILECONFIGURATORDEFS_H */
