
include top.mak

SRCS = \
	gentestdata.cpp

X_CFLAGS = \
	$(BOOST_INCLUDE) \

X_LIBS = \

X_THIRDPARTY_LIBS = \
	$(BOOST_LIBS) \

X_SYSTEM_LIBS =

X_LDFLAGS =

BINARY=gentestdata
BINARY_EXT=$(X_EXEEXT)

include bottom.mak
